import type {
  ModuleFieldOption,
  ModuleOptionCompatibility,
  ModuleSubjectType,
  PromptKeyModule,
} from "./types";

const PROPORTION_CONFLICT_WARNING =
  "modules.form.compatibility.transformationProportionConflict";

function option(
  value: string,
  promptText: string,
  tags: string[] = [],
  config: {
    category?: string;
    categoryLabelKey?: string;
    appliesTo?: Array<ModuleSubjectType | "*">;
    compatibility?: ModuleOptionCompatibility;
  } = {},
): ModuleFieldOption {
  return {
    value,
    promptText,
    tags,
    ...config,
  };
}

const formLanguageOptions: ModuleFieldOption[] = [
  option("soft_rounded", "soft rounded form language with smooth contours", ["soft", "rounded"]),
  option("geometric", "geometric form language with simplified structural shapes", ["geometric", "structured"]),
  option("fluid_organic", "fluid organic form language with continuous curves", ["fluid", "organic"]),
  option("blocky", "blocky form language with simplified squared geometry", ["blocky", "squared"]),
  option("angular", "angular form language with sharp directional edges", ["angular", "sharp"]),
  option("irregular", "irregular asymmetric form language with uneven contours", ["irregular", "asymmetric"]),
  option("faceted", "faceted planar form language with distinct angular breaks", ["faceted", "planar"]),
  option("biomorphic", "biomorphic form language with soft irregular organic masses", ["biomorphic", "organic"]),
  option("monolithic", "monolithic form language built from large unified masses", ["monolithic", "massive"]),
  option("branching", "branching form language with extending interconnected forms", ["branching", "organic"]),
  option("ribbon_like", "ribbon-like form language with broad continuous bands", ["ribbon", "flowing"]),
  option("crystalline", "crystalline form language with repeated angular facets", ["crystalline", "faceted"]),
  option("layered", "layered form language built from stacked overlapping masses", ["layered", "stacked"]),
  option("cellular", "cellular form language built from clustered repeated units", ["cellular", "repeated"]),
  option("radial", "radial form language with structures extending around central axes", ["radial", "branching"]),
  option("modular_letterforms", "modular letterform language built from repeated geometric units", ["typography", "modular", "geometric"], { appliesTo: ["typography"] }),
  option("ribbon_letterforms", "ribbon-like letterforms built from continuous folded strokes", ["typography", "ribbon", "flowing"], { appliesTo: ["typography"] }),
  option("inflated_letterforms", "inflated letterforms with rounded volumetric strokes", ["typography", "inflated", "rounded"], { appliesTo: ["typography"] }),
  option("interlocking_letterforms", "interlocking letterforms with structurally woven stroke connections", ["typography", "interlocking", "woven"], { appliesTo: ["typography"] }),
  option("terraced_environment", "terraced environmental form language with stepped layered masses", ["scene", "terraced", "layered"], { appliesTo: ["scene"] }),
  option("stratified_environment", "stratified environmental form language with clearly separated structural layers", ["scene", "stratified", "layered"], { appliesTo: ["scene"] }),
  option("eroded_environment", "eroded environmental form language with carved irregular contours", ["scene", "eroded", "irregular"], { appliesTo: ["scene"] }),
  option("dendritic_environment", "dendritic environmental form language with branching channel-like structures", ["scene", "dendritic", "branching"], { appliesTo: ["scene"] }),
  option("streamlined_animal", "streamlined animal form language with smooth tapered contours", ["animal", "streamlined", "tapered"], { appliesTo: ["animal"] }),
  option("segmented_animal", "segmented animal form language with articulated repeating body sections", ["animal", "segmented", "articulated"], { appliesTo: ["animal"] }),
  option("armored_animal", "armored animal form language with overlapping plate-like body sections", ["animal", "armored", "layered"], { appliesTo: ["animal"] }),
  option("serpentine_animal", "serpentine animal form language with sinuous continuous body flow", ["animal", "serpentine", "elongated"], { appliesTo: ["animal"] }),
];

const proportionOptions: ModuleFieldOption[] = [
  option("balanced", "balanced proportions with even visual mass distribution", ["balanced"], { category: "general", categoryLabelKey: "modules.form.fields.proportions.categories.general" }),
  option("elongated", "elongated proportions with extended overall form", ["elongated"], { category: "general", categoryLabelKey: "modules.form.fields.proportions.categories.general" }),
  option("compact", "compact proportions with shortened overall form", ["compact"], { category: "general", categoryLabelKey: "modules.form.fields.proportions.categories.general" }),
  option("wide", "wide proportions with expanded horizontal mass", ["wide"], { category: "general", categoryLabelKey: "modules.form.fields.proportions.categories.general" }),
  option("tapered", "tapered proportions with progressively narrowing forms", ["tapered"], { category: "general", categoryLabelKey: "modules.form.fields.proportions.categories.general" }),
  option("top_heavy", "top-heavy proportions with greater visual mass in the upper form", ["top-heavy"], { category: "general", categoryLabelKey: "modules.form.fields.proportions.categories.general" }),
  option("bottom_heavy", "bottom-heavy proportions with greater visual mass in the lower form", ["bottom-heavy"], { category: "general", categoryLabelKey: "modules.form.fields.proportions.categories.general" }),
  option("asymmetric", "asymmetric proportions with deliberately uneven mass distribution", ["asymmetric"], { category: "general", categoryLabelKey: "modules.form.fields.proportions.categories.general" }),
  option("oversized_elements", "selectively oversized proportions with emphasized major elements", ["oversized"], { category: "general", categoryLabelKey: "modules.form.fields.proportions.categories.general" }),
  option("graduated_scale", "graduated proportions with elements changing progressively in scale", ["graduated", "scale"], { category: "general", categoryLabelKey: "modules.form.fields.proportions.categories.general" }),
  option("nested_scale", "nested proportions with smaller forms contained within larger masses", ["nested", "scale"], { category: "general", categoryLabelKey: "modules.form.fields.proportions.categories.general" }),
  option("chibi", "chibi proportions with an oversized head, compact body, and short limbs", ["person", "chibi", "compact"], { category: "person", categoryLabelKey: "modules.form.fields.proportions.categories.person", appliesTo: ["person"] }),
  option("slender_elongated", "slender elongated proportions with long limbs and a narrow torso", ["person", "slender", "elongated", "long-limbed"], { category: "person", categoryLabelKey: "modules.form.fields.proportions.categories.person", appliesTo: ["person"] }),
  option("oversized_head", "an oversized head-to-body ratio with a compact supporting body", ["person", "head", "oversized", "compact"], { category: "person", categoryLabelKey: "modules.form.fields.proportions.categories.person", appliesTo: ["person"] }),
  option("compact_short_limb", "compact body proportions with short limbs and concentrated central mass", ["person", "compact", "short-limbed"], { category: "person", categoryLabelKey: "modules.form.fields.proportions.categories.person", appliesTo: ["person"] }),
  option("long_limb_narrow_torso", "long-limbed proportions with a narrow torso and extended body rhythm", ["person", "long-limbed", "narrow", "elongated"], { category: "person", categoryLabelKey: "modules.form.fields.proportions.categories.person", appliesTo: ["person"] }),
  option("long_torso_short_legs", "a long torso paired with shortened leg proportions", ["person", "long-torso", "short-limbed"], { category: "person", categoryLabelKey: "modules.form.fields.proportions.categories.person", appliesTo: ["person"] }),
  option("short_torso_long_legs", "a short torso paired with elongated leg proportions", ["person", "short-torso", "long-limbed", "elongated"], { category: "person", categoryLabelKey: "modules.form.fields.proportions.categories.person", appliesTo: ["person"] }),
  option("broad_shoulders_narrow_hips", "broad shoulder proportions tapering toward narrower hips", ["person", "broad-shoulders", "tapered"], { category: "person", categoryLabelKey: "modules.form.fields.proportions.categories.person", appliesTo: ["person"] }),
  option("narrow_shoulders_wide_hips", "narrow shoulder proportions expanding toward wider hips", ["person", "wide-hips", "bottom-heavy"], { category: "person", categoryLabelKey: "modules.form.fields.proportions.categories.person", appliesTo: ["person"] }),
  option("oversized_hands_feet", "oversized hand and foot proportions relative to the body", ["person", "oversized", "extremities"], { category: "person", categoryLabelKey: "modules.form.fields.proportions.categories.person", appliesTo: ["person"] }),
  option("type_condensed", "condensed letterform proportions with narrow glyph width", ["typography", "condensed", "narrow"], { category: "typography", categoryLabelKey: "modules.form.fields.proportions.categories.typography", appliesTo: ["typography"] }),
  option("type_expanded", "expanded letterform proportions with broad glyph width", ["typography", "expanded", "wide"], { category: "typography", categoryLabelKey: "modules.form.fields.proportions.categories.typography", appliesTo: ["typography"] }),
  option("type_tall_narrow", "tall narrow letterform proportions with extended vertical strokes", ["typography", "tall", "narrow", "elongated"], { category: "typography", categoryLabelKey: "modules.form.fields.proportions.categories.typography", appliesTo: ["typography"] }),
  option("type_squat_wide", "squat wide letterform proportions with compressed height and broad width", ["typography", "squat", "wide", "compact"], { category: "typography", categoryLabelKey: "modules.form.fields.proportions.categories.typography", appliesTo: ["typography"] }),
  option("type_variable_scale", "variable letterform proportions with deliberately mixed glyph scale", ["typography", "variable", "scale"], { category: "typography", categoryLabelKey: "modules.form.fields.proportions.categories.typography", appliesTo: ["typography"] }),
  option("scene_towering", "towering environmental proportions with dominant vertical masses", ["scene", "towering", "elongated"], { category: "scene", categoryLabelKey: "modules.form.fields.proportions.categories.scene", appliesTo: ["scene"] }),
  option("scene_low_spreading", "low spreading environmental proportions with broad shallow masses", ["scene", "low", "wide"], { category: "scene", categoryLabelKey: "modules.form.fields.proportions.categories.scene", appliesTo: ["scene"] }),
  option("scene_narrow_vertical", "narrow vertical environmental proportions with slender rising forms", ["scene", "narrow", "elongated"], { category: "scene", categoryLabelKey: "modules.form.fields.proportions.categories.scene", appliesTo: ["scene"] }),
  option("scene_broad_horizontal", "broad horizontal environmental proportions with extended low forms", ["scene", "wide", "horizontal"], { category: "scene", categoryLabelKey: "modules.form.fields.proportions.categories.scene", appliesTo: ["scene"] }),
  option("scene_scale_gradient", "graduated environmental proportions with masses progressing from small to large", ["scene", "graduated", "scale"], { category: "scene", categoryLabelKey: "modules.form.fields.proportions.categories.scene", appliesTo: ["scene"] }),
  option("animal_long_body_short_limbs", "long-bodied animal proportions with comparatively short limbs", ["animal", "long-body", "short-limbed", "elongated"], { category: "animal", categoryLabelKey: "modules.form.fields.proportions.categories.animal", appliesTo: ["animal"] }),
  option("animal_long_legged", "long-legged animal proportions with elevated body height", ["animal", "long-limbed", "elongated"], { category: "animal", categoryLabelKey: "modules.form.fields.proportions.categories.animal", appliesTo: ["animal"] }),
  option("animal_compact_stocky", "compact stocky animal proportions with concentrated body mass", ["animal", "compact", "stocky"], { category: "animal", categoryLabelKey: "modules.form.fields.proportions.categories.animal", appliesTo: ["animal"] }),
  option("animal_large_head_small_body", "a large head-to-body ratio with a smaller supporting body", ["animal", "oversized", "head", "compact"], { category: "animal", categoryLabelKey: "modules.form.fields.proportions.categories.animal", appliesTo: ["animal"] }),
  option("animal_long_neck", "an elongated neck proportion relative to the torso mass", ["animal", "long-neck", "elongated"], { category: "animal", categoryLabelKey: "modules.form.fields.proportions.categories.animal", appliesTo: ["animal"] }),
  option("animal_tapered_body", "animal body proportions tapering from a broad front mass toward a narrower rear form", ["animal", "tapered"], { category: "animal", categoryLabelKey: "modules.form.fields.proportions.categories.animal", appliesTo: ["animal"] }),
];

const transformationOptions: ModuleFieldOption[] = [
  option("stretch", "stretched form", ["stretch", "elastic", "elongated"], { category: "elastic", categoryLabelKey: "modules.form.fields.transformation.categories.elastic" }),
  option("squash", "squashed form", ["squash", "elastic", "compact"], { category: "elastic", categoryLabelKey: "modules.form.fields.transformation.categories.elastic" }),
  option("elastic_bend", "elastic bending with continuous flexible curvature", ["elastic", "bend", "fluid"], { category: "elastic", categoryLabelKey: "modules.form.fields.transformation.categories.elastic" }),
  option("compress", "compressed form", ["compressed", "volume", "compact"], { category: "volume", categoryLabelKey: "modules.form.fields.transformation.categories.volume" }),
  option("inflate", "inflated form with expanded volume", ["inflated", "volume", "wide"], { category: "volume", categoryLabelKey: "modules.form.fields.transformation.categories.volume" }),
  option("flatten", "flattened form with reduced depth", ["flattened", "planar"], { category: "volume", categoryLabelKey: "modules.form.fields.transformation.categories.volume" }),
  option("pinch", "pinched form with localized narrowing", ["pinch", "narrow", "tapered"], { category: "volume", categoryLabelKey: "modules.form.fields.transformation.categories.volume" }),
  option("bulge", "localized bulging with expanded form mass", ["bulge", "volume", "wide"], { category: "volume", categoryLabelKey: "modules.form.fields.transformation.categories.volume" }),
  option("twist", "twisted form with rotational curvature", ["twist", "warp"], { category: "warp", categoryLabelKey: "modules.form.fields.transformation.categories.warp" }),
  option("warp", "warped form with displaced structure", ["warp", "distort"], { category: "warp", categoryLabelKey: "modules.form.fields.transformation.categories.warp" }),
  option("melt", "melting form with downward droop", ["melt", "droop"], { category: "warp", categoryLabelKey: "modules.form.fields.transformation.categories.warp" }),
  option("fold", "folded form with articulated bends", ["fold", "bend", "planar"], { category: "warp", categoryLabelKey: "modules.form.fields.transformation.categories.warp" }),
  option("ripple", "rippled form with repeated wave-like deformation", ["ripple", "wave", "fluid"], { category: "warp", categoryLabelKey: "modules.form.fields.transformation.categories.warp" }),
  option("spiral", "spiraled form with continuous rotational winding", ["spiral", "twist", "flow"], { category: "warp", categoryLabelKey: "modules.form.fields.transformation.categories.warp" }),
  option("fragment", "fragmented form with separated structural pieces", ["fragment", "structural"], { category: "structural", categoryLabelKey: "modules.form.fields.transformation.categories.structural" }),
  option("offset_segments", "offset segmented form with displaced structural sections", ["segmented", "offset", "structural"], { category: "structural", categoryLabelKey: "modules.form.fields.transformation.categories.structural" }),
  option("fractured_planes", "fractured planar form with shifted angular sections", ["fractured", "planes", "structural"], { category: "structural", categoryLabelKey: "modules.form.fields.transformation.categories.structural" }),
  option("perforate", "perforated form with deliberate structural voids", ["perforated", "voids", "structural"], { category: "structural", categoryLabelKey: "modules.form.fields.transformation.categories.structural" }),
  option("interweave", "interwoven form with crossing structural bands", ["interwoven", "structural", "ribbon"], { category: "structural", categoryLabelKey: "modules.form.fields.transformation.categories.structural" }),
  option("directional_smear", "directionally smeared form with trailing stretched shapes", ["smear", "directional", "elongated"], { category: "surreal", categoryLabelKey: "modules.form.fields.transformation.categories.surreal" }),
  option("impossible_geometry", "impossible geometry with coherent impossible connections", ["impossible", "surreal"], { category: "surreal", categoryLabelKey: "modules.form.fields.transformation.categories.surreal" }),
  option("biomorphic_growth", "biomorphic growth with uneven organic extensions", ["biomorphic", "growth", "organic"], { category: "surreal", categoryLabelKey: "modules.form.fields.transformation.categories.surreal" }),
  option("grotesque_caricature", "grotesque anatomical exaggeration with awkward proportional imbalance", ["person", "caricature", "grotesque", "asymmetric"], { category: "person_caricature", categoryLabelKey: "modules.form.fields.transformation.categories.personCaricature", appliesTo: ["person"] }),
  option("elegant_caricature", "elegant anatomical exaggeration with sharpened facial planes and controlled proportional distortion", ["person", "caricature", "elegant", "elongated"], { category: "person_caricature", categoryLabelKey: "modules.form.fields.transformation.categories.personCaricature", appliesTo: ["person"] }),
  option("facial_exaggeration", "facial exaggeration with enlarged features and altered head proportions", ["person", "face", "exaggeration", "oversized"], { category: "person_caricature", categoryLabelKey: "modules.form.fields.transformation.categories.personCaricature", appliesTo: ["person"] }),
  option("anatomical_asymmetry", "anatomical asymmetry with uneven proportional balance", ["person", "asymmetry", "caricature"], { category: "person_caricature", categoryLabelKey: "modules.form.fields.transformation.categories.personCaricature", appliesTo: ["person"] }),
  option("rubber_hose_anatomy", "rubber-hose anatomy with flexible jointless limbs and rounded bends", ["person", "rubber-hose", "elastic", "rounded"], { category: "person_elastic", categoryLabelKey: "modules.form.fields.transformation.categories.personElastic", appliesTo: ["person"] }),
  option("spring_loaded_anatomy", "spring-loaded anatomy with elongated limbs and compressed body sections", ["person", "spring", "elastic", "elongated"], { category: "person_elastic", categoryLabelKey: "modules.form.fields.transformation.categories.personElastic", appliesTo: ["person"] }),
  option("balloon_anatomy", "inflated anatomy with rounded body volumes and puffed limbs", ["person", "inflated", "balloon", "wide"], { category: "person_elastic", categoryLabelKey: "modules.form.fields.transformation.categories.personElastic", appliesTo: ["person"] }),
  option("squashed_compact_anatomy", "squashed compact anatomy with shortened body proportions", ["person", "squashed", "compact", "short-limbed"], { category: "person_elastic", categoryLabelKey: "modules.form.fields.transformation.categories.personElastic", appliesTo: ["person"], compatibility: { preferredTags: ["compact", "chibi", "short-limbed"], discouragedTags: ["elongated", "long-limbed", "slender"], warningKey: PROPORTION_CONFLICT_WARNING } }),
  option("marionette_anatomy", "marionette-like anatomy with jointed limbs and segmented body construction", ["person", "marionette", "jointed", "segmented"], { category: "person_constructed", categoryLabelKey: "modules.form.fields.transformation.categories.personConstructed", appliesTo: ["person"] }),
  option("mannequin_anatomy", "mannequin-like anatomy with simplified rigid segmentation", ["person", "mannequin", "segmented", "rigid"], { category: "person_constructed", categoryLabelKey: "modules.form.fields.transformation.categories.personConstructed", appliesTo: ["person"] }),
  option("cuboid_anatomy", "cuboid anatomy with squared limbs and block-built body sections", ["person", "cuboid", "blocky"], { category: "person_constructed", categoryLabelKey: "modules.form.fields.transformation.categories.personConstructed", appliesTo: ["person"] }),
  option("faceted_anatomy", "faceted anatomy built from sharp planar body sections", ["person", "faceted", "polygonal"], { category: "person_constructed", categoryLabelKey: "modules.form.fields.transformation.categories.personConstructed", appliesTo: ["person"] }),
  option("insectoid_anatomy", "insectoid anatomy with segmented limbs and articulated joints", ["person", "animal", "insectoid", "segmented"], { category: "person_creature", categoryLabelKey: "modules.form.fields.transformation.categories.personCreature", appliesTo: ["person", "animal"] }),
  option("creature_hybrid", "hybridized anatomy with altered limb structure and nonhuman proportional balance", ["person", "animal", "creature", "hybrid"], { category: "person_creature", categoryLabelKey: "modules.form.fields.transformation.categories.personCreature", appliesTo: ["person", "animal"] }),
  option("alien_elongation", "alien-like anatomical restructuring with unfamiliar nonhuman body ratios", ["person", "alien", "elongated", "long-limbed"], { category: "person_creature", categoryLabelKey: "modules.form.fields.transformation.categories.personCreature", appliesTo: ["person"], compatibility: { preferredTags: ["elongated", "long-limbed", "slender"], discouragedTags: ["compact", "chibi", "short-limbed", "stocky"], warningKey: PROPORTION_CONFLICT_WARNING } }),
  option("grotesque_misshapen", "grotesque misshapen anatomy with irregular proportions and deliberate asymmetry", ["person", "grotesque", "misshapen", "asymmetric"], { category: "person_grotesque", categoryLabelKey: "modules.form.fields.transformation.categories.personGrotesque", appliesTo: ["person"] }),
  option("distorted_elegance", "elegant anatomical distortion with controlled uncanny imbalance", ["person", "grotesque", "elegant", "elongated"], { category: "person_grotesque", categoryLabelKey: "modules.form.fields.transformation.categories.personGrotesque", appliesTo: ["person"] }),
  option("radical_silhouette", "radically altered body silhouette with redistributed width, length, and mass", ["person", "silhouette", "radical"], { category: "person_grotesque", categoryLabelKey: "modules.form.fields.transformation.categories.personGrotesque", appliesTo: ["person"] }),
  option("pinched_torso", "pinched torso anatomy with narrowed central body mass", ["person", "pinched", "narrow"], { category: "person_grotesque", categoryLabelKey: "modules.form.fields.transformation.categories.personGrotesque", appliesTo: ["person"] }),
  option("limb_taper", "tapered limb anatomy with progressively narrowing extremities", ["person", "limb", "tapered"], { category: "person_grotesque", categoryLabelKey: "modules.form.fields.transformation.categories.personGrotesque", appliesTo: ["person"] }),
  option("type_arc_bend", "letterforms bent along a smooth structural arc", ["typography", "bend", "arc"], { category: "typography", categoryLabelKey: "modules.form.fields.transformation.categories.typography", appliesTo: ["typography"] }),
  option("type_wave", "letterforms warped into repeating wave curvature", ["typography", "wave", "fluid"], { category: "typography", categoryLabelKey: "modules.form.fields.transformation.categories.typography", appliesTo: ["typography"] }),
  option("type_inflate", "inflated letterforms with expanded rounded stroke volume", ["typography", "inflated", "rounded", "wide"], { category: "typography", categoryLabelKey: "modules.form.fields.transformation.categories.typography", appliesTo: ["typography"] }),
  option("type_pinch", "pinched letterforms with localized stroke narrowing", ["typography", "pinch", "narrow"], { category: "typography", categoryLabelKey: "modules.form.fields.transformation.categories.typography", appliesTo: ["typography"] }),
  option("type_fold", "folded letterforms with articulated planar bends", ["typography", "fold", "planar"], { category: "typography", categoryLabelKey: "modules.form.fields.transformation.categories.typography", appliesTo: ["typography"] }),
  option("type_interlock", "interlocking letterforms with structural overlap between glyph forms", ["typography", "interlock", "structural"], { category: "typography", categoryLabelKey: "modules.form.fields.transformation.categories.typography", appliesTo: ["typography"] }),
  option("type_fragment", "fragmented letterforms with separated glyph sections", ["typography", "fragment", "structural"], { category: "typography", categoryLabelKey: "modules.form.fields.transformation.categories.typography", appliesTo: ["typography"] }),
  option("type_twist", "twisted letterform strokes with controlled rotational deformation", ["typography", "twist", "warp"], { category: "typography", categoryLabelKey: "modules.form.fields.transformation.categories.typography", appliesTo: ["typography"] }),
  option("scene_terrain_fold", "environmental masses folded into broad ridge formations", ["scene", "fold", "layered"], { category: "scene", categoryLabelKey: "modules.form.fields.transformation.categories.scene", appliesTo: ["scene"] }),
  option("scene_sweeping_warp", "environmental forms warped into sweeping continuous curves", ["scene", "warp", "fluid"], { category: "scene", categoryLabelKey: "modules.form.fields.transformation.categories.scene", appliesTo: ["scene"] }),
  option("scene_floating_masses", "environmental masses separated into floating structural islands", ["scene", "floating", "fragment"], { category: "scene", categoryLabelKey: "modules.form.fields.transformation.categories.scene", appliesTo: ["scene"] }),
  option("scene_strata_shift", "environmental strata offset into displaced terraces", ["scene", "stratified", "offset"], { category: "scene", categoryLabelKey: "modules.form.fields.transformation.categories.scene", appliesTo: ["scene"] }),
  option("scene_crystalline_growth", "crystalline environmental growth with expanding faceted structures", ["scene", "crystalline", "growth", "faceted"], { category: "scene", categoryLabelKey: "modules.form.fields.transformation.categories.scene", appliesTo: ["scene"] }),
  option("scene_erosion_cut", "erosion-like transformation with carved channels and recessed masses", ["scene", "erosion", "carved"], { category: "scene", categoryLabelKey: "modules.form.fields.transformation.categories.scene", appliesTo: ["scene"] }),
  option("scene_gravity_droop", "environmental forms drooping downward under exaggerated gravity", ["scene", "droop", "gravity"], { category: "scene", categoryLabelKey: "modules.form.fields.transformation.categories.scene", appliesTo: ["scene"] }),
  option("scene_inverted_landform", "inverted environmental geometry with overhanging and reversed structural masses", ["scene", "inverted", "surreal"], { category: "scene", categoryLabelKey: "modules.form.fields.transformation.categories.scene", appliesTo: ["scene"] }),
  option("animal_serpentine_elongation", "serpentine anatomical restructuring with pronounced winding curvature", ["animal", "serpentine", "elongated", "long-body"], { category: "animal", categoryLabelKey: "modules.form.fields.transformation.categories.animal", appliesTo: ["animal"], compatibility: { preferredTags: ["elongated", "long-body", "long-neck"], discouragedTags: ["compact", "stocky"], warningKey: PROPORTION_CONFLICT_WARNING } }),
  option("animal_multi_limb", "multilimbed anatomical transformation with additional articulated appendages", ["animal", "multi-limb", "segmented"], { category: "animal", categoryLabelKey: "modules.form.fields.transformation.categories.animal", appliesTo: ["animal"] }),
  option("animal_armored_segmentation", "animal anatomy segmented into overlapping plate-like body sections", ["animal", "armored", "segmented"], { category: "animal", categoryLabelKey: "modules.form.fields.transformation.categories.animal", appliesTo: ["animal"] }),
  option("animal_spine_growth", "spine-like structural growth extending along the body silhouette", ["animal", "spines", "growth"], { category: "animal", categoryLabelKey: "modules.form.fields.transformation.categories.animal", appliesTo: ["animal"] }),
  option("animal_limb_reduction", "reduced limb anatomy with shortened or minimized appendages", ["animal", "limb", "reduced", "compact"], { category: "animal", categoryLabelKey: "modules.form.fields.transformation.categories.animal", appliesTo: ["animal"] }),
  option("animal_appendage_expansion", "expanded major appendage forms with broader structural span", ["animal", "appendage", "expanded", "wide"], { category: "animal", categoryLabelKey: "modules.form.fields.transformation.categories.animal", appliesTo: ["animal"] }),
];

const transformationStrengthOptions: ModuleFieldOption[] = [
  option("subtle", "subtle form transformation", ["subtle"]),
  option("moderate", "moderate form transformation", ["moderate"]),
  option("strong", "strong form transformation", ["strong"]),
  option("extreme", "extreme form transformation", ["extreme"]),
];

export const FormModule: PromptKeyModule = {
  key: "form",
  icon: "transform",
  groups: {
    core: { id: "core", order: 10, defaultOpen: true },
    transformation: { id: "transformation", order: 20, defaultOpen: true },
    advanced: { id: "advanced", order: 30, defaultOpen: false },
    override: { id: "override", order: 40, defaultOpen: false },
  },
  fields: {
    formLanguage: {
      id: "formLanguage",
      type: "select",
      default: "",
      group: "core",
      order: 10,
      options: formLanguageOptions,
      ui: { component: "select", searchable: true, clearable: true, width: "half" },
    },
    proportions: {
      id: "proportions",
      type: "select",
      default: "",
      group: "core",
      order: 20,
      options: proportionOptions,
      ui: { component: "select", optionLayout: "categorized", searchable: true, clearable: true, width: "half" },
    },
    transformation: {
      id: "transformation",
      type: "select",
      default: "",
      group: "transformation",
      order: 10,
      options: transformationOptions,
      ui: {
        component: "select",
        optionLayout: "categorized",
        searchable: true,
        clearable: true,
        width: "full",
        compatibility: { dependsOn: "proportions", mode: "sort-and-hint" },
      },
    },
    transformationStrength: {
      id: "transformationStrength",
      type: "select",
      default: "",
      group: "transformation",
      order: 20,
      options: transformationStrengthOptions,
      ui: { component: "select", clearable: true, width: "half" },
    },
    extraDetails: {
      id: "extraDetails",
      type: "textarea",
      default: "",
      group: "advanced",
      order: 10,
      ui: { component: "textarea", rows: 3, width: "full" },
    },
    customText: {
      id: "customText",
      type: "textarea",
      default: "",
      group: "override",
      order: 10,
      isOverride: true,
      ui: { component: "textarea", rows: 4, width: "full" },
    },
  },
  compile: {
    separator: ", ",
    removeDuplicates: true,
    ignoreEmpty: true,
    overrideField: "customText",
    fieldOrder: ["formLanguage", "proportions", "transformation", "transformationStrength", "extraDetails"],
  },
};
