import type { PromptKeyModule } from "./types";

const stylePresetOptions = [
  {
    value: "3d_cartoon",
    promptText:
      "stylized 3D cartoon character design, toy-like exaggerated forms, clean cel-shaded surfaces",
    tags: ["3d", "cartoon", "stylized"],
  },
  {
    value: "anime_cover",
    promptText:
      "anime cover illustration, expressive character design, dynamic stylized visual language",
    tags: ["anime", "illustration", "stylized"],
  },
  {
    value: "cinematic_realism",
    promptText:
      "cinematic realistic image style, film-like atmosphere, detailed natural rendering",
    tags: ["cinematic", "realistic"],
  },
  {
    value: "clay_sculpture",
    promptText:
      "handcrafted clay sculpture style, soft sculpted forms, tactile handmade surface",
    tags: ["sculpture", "clay", "handmade"],
  },
  {
    value: "vinyl_toy",
    promptText:
      "premium vinyl toy design, smooth rounded forms, collectible figure aesthetic",
    tags: ["toy", "vinyl", "3d"],
  },
  {
    value: "geometric_editorial",
    promptText:
      "bold geometric editorial illustration, simplified angular shapes, flat color block construction",
    tags: ["geometric", "editorial", "flat"],
  },
  {
    value: "primitive_cut_paper",
    promptText:
      "primitive flat cut-paper caricature portrait, assembled from simple oversized paper-like shapes",
    tags: ["cut-paper", "primitive", "flat"],
  },
  {
    value: "retro_comic",
    promptText:
      "retro comic book illustration, bold black outlines, graphic contrast, stylized pop-art energy",
    tags: ["comic", "retro", "pop-art"],
  },
  {
    value: "fashion_caricature_sketch",
    promptText:
      "grotesque humorous fashion caricature sketch, satirical editorial energy, exaggerated anatomy",
    tags: ["fashion", "caricature", "sketch"],
  },
  {
    value: "angular_animation",
    promptText:
      "minimalist angular 2D animation aesthetic, bold graphic silhouettes, sharp geometric forms",
    tags: ["angular", "animation", "minimalist"],
  },
  {
    value: "childlike_drawing",
    promptText:
      "naive childlike drawing style, amateur colored-pencil artwork, strange simplified anatomy",
    tags: ["childlike", "drawing", "amateur"],
  },
  {
    value: "low_poly_3d",
    promptText:
      "low-poly 3D character design, faceted simplified geometry, stylized polygonal forms",
    tags: ["low-poly", "3d", "geometric"],
  },
  {
    value: "watercolor_editorial",
    promptText:
      "watercolor editorial illustration, fluid organic forms, expressive ink and watercolor treatment, clean artistic finish",
    tags: ["watercolor", "editorial", "illustration"],
  },
  {
    value: "crafted_paper_collage",
    promptText:
      "crafted paper collage artwork, layered paper construction, simplified blocky forms, handmade tactile finish",
    tags: ["paper", "collage", "handcrafted"],
  },
  {
    value: "low_poly_character",
    promptText:
      "low-poly character design, geometric simplified forms, strong stylization, minimalist visual treatment, clean polished finish",
    tags: ["low-poly", "3d", "geometric"],
  },
  {
    value: "pixel_art_game_character",
    promptText:
      "pixel-art game character design, blocky simplified forms, strong stylization, minimalist visual treatment, bold graphic finish",
    tags: ["pixel-art", "game", "graphic"],
  },
  {
    value: "risograph_poster_art",
    promptText:
      "risograph poster artwork, geometric structured forms, controlled stylization, flat graphic treatment, bold graphic finish",
    tags: ["risograph", "poster", "graphic"],
  },
  {
    value: "ink_character_sketch",
    promptText:
      "ink character sketch, fluid organic forms, controlled stylization, expressive ink and watercolor treatment, rough artistic finish",
    tags: ["ink", "sketch", "character"],
  },
  {
    value: "cinematic_cgi_character",
    promptText:
      "cinematic CGI character design, soft rounded forms, controlled stylization, expressive painted treatment, premium polished finish",
    tags: ["cgi", "cinematic", "character"],
  },
  {
    value: "studio_photo_realism",
    promptText:
      "studio photo realism, fluid natural forms, subtle stylization, minimalist visual treatment, clean polished finish",
    tags: ["studio", "photo", "realism"],
  },
  {
    value: "papier_mache_character",
    promptText:
      "papier-mâché character design, angular simplified forms, extreme stylization, minimalist visual treatment, handcrafted tactile finish",
    tags: ["papier-mache", "handcrafted", "character"],
  },
  {
    value: "plush_toy_character",
    promptText:
      "plush toy character design, soft rounded forms, strong stylization, minimalist visual treatment, handcrafted tactile finish",
    tags: ["plush", "toy", "character"],
  },
  {
    value: "woodcut_editorial",
    promptText:
      "woodcut editorial artwork, angular graphic forms, strong stylization, flat graphic treatment, rough print-like finish",
    tags: ["woodcut", "editorial", "print"],
  },
  {
    value: "marker_concept_art",
    promptText:
      "marker concept art, geometric structured forms, controlled stylization, expressive hand-painted treatment, clean visual finish",
    tags: ["marker", "concept-art", "illustration"],
  },
];

const mediumOptions = [
  // Digital / CG
  {
    value: "digital_illustration",
    category: "digital_cg",
    categoryLabel: "Digital / CG",
    promptText: "high-end digital illustration",
    tags: ["digital", "illustration"],
  },
  {
    value: "digital_painting",
    category: "digital_cg",
    categoryLabel: "Digital / CG",
    promptText: "digital painting artwork",
    tags: ["digital", "painting"],
  },
  {
    value: "vector_illustration",
    category: "digital_cg",
    categoryLabel: "Digital / CG",
    promptText: "clean vector illustration",
    tags: ["vector", "illustration"],
  },
  {
    value: "three_d_render",
    category: "digital_cg",
    categoryLabel: "Digital / CG",
    promptText: "high-quality 3D render",
    tags: ["3d", "render"],
  },
  {
    value: "cgi",
    category: "digital_cg",
    categoryLabel: "Digital / CG",
    promptText: "cinematic CGI rendering",
    tags: ["cgi", "render"],
  },
  {
    value: "game_asset_render",
    category: "digital_cg",
    categoryLabel: "Digital / CG",
    promptText: "game asset style 3D render",
    tags: ["game", "3d", "asset"],
  },
  {
    value: "low_poly_render",
    category: "digital_cg",
    categoryLabel: "Digital / CG",
    promptText: "low-poly 3D render",
    tags: ["low-poly", "3d"],
  },
  {
    value: "pixel_art_digital",
    category: "digital_cg",
    categoryLabel: "Digital / CG",
    promptText: "digital pixel art",
    tags: ["pixel-art", "digital"],
  },

  // Drawing
  {
    value: "pencil_drawing",
    category: "drawing",
    categoryLabel: "Drawing",
    promptText: "pencil drawing",
    tags: ["pencil", "drawing"],
  },
  {
    value: "colored_pencil_drawing",
    category: "drawing",
    categoryLabel: "Drawing",
    promptText: "colored pencil drawing",
    tags: ["colored-pencil", "drawing"],
  },
  {
    value: "charcoal_drawing",
    category: "drawing",
    categoryLabel: "Drawing",
    promptText: "charcoal drawing",
    tags: ["charcoal", "drawing"],
  },
  {
    value: "ink_drawing",
    category: "drawing",
    categoryLabel: "Drawing",
    promptText: "ink drawing",
    tags: ["ink", "drawing"],
  },
  {
    value: "pen_and_ink",
    category: "drawing",
    categoryLabel: "Drawing",
    promptText: "pen and ink illustration",
    tags: ["pen", "ink", "illustration"],
  },
  {
    value: "marker_render",
    category: "drawing",
    categoryLabel: "Drawing",
    promptText: "marker rendering",
    tags: ["marker", "drawing"],
  },
  {
    value: "pastel_drawing",
    category: "drawing",
    categoryLabel: "Drawing",
    promptText: "pastel drawing",
    tags: ["pastel", "drawing"],
  },

  // Painting
  {
    value: "watercolor_painting",
    category: "painting",
    categoryLabel: "Painting",
    promptText: "watercolor painting",
    tags: ["watercolor", "painting"],
  },
  {
    value: "gouache_painting",
    category: "painting",
    categoryLabel: "Painting",
    promptText: "gouache painting",
    tags: ["gouache", "painting"],
  },
  {
    value: "oil_painting",
    category: "painting",
    categoryLabel: "Painting",
    promptText: "oil painting",
    tags: ["oil", "painting"],
  },
  {
    value: "acrylic_painting",
    category: "painting",
    categoryLabel: "Painting",
    promptText: "acrylic painting",
    tags: ["acrylic", "painting"],
  },
  {
    value: "ink_and_wash",
    category: "painting",
    categoryLabel: "Painting",
    promptText: "ink and wash painting",
    tags: ["ink", "wash", "painting"],
  },

  // Printmaking
  {
    value: "screen_print",
    category: "printmaking",
    categoryLabel: "Printmaking",
    promptText: "screen print artwork",
    tags: ["screen-print", "printmaking"],
  },
  {
    value: "risograph_print",
    category: "printmaking",
    categoryLabel: "Printmaking",
    promptText: "risograph print style",
    tags: ["risograph", "printmaking"],
  },
  {
    value: "linocut_print",
    category: "printmaking",
    categoryLabel: "Printmaking",
    promptText: "linocut print",
    tags: ["linocut", "printmaking"],
  },
  {
    value: "woodcut_print",
    category: "printmaking",
    categoryLabel: "Printmaking",
    promptText: "woodcut print",
    tags: ["woodcut", "printmaking"],
  },
  {
    value: "etching_print",
    category: "printmaking",
    categoryLabel: "Printmaking",
    promptText: "etched printmaking style",
    tags: ["etching", "printmaking"],
  },

  // Photography
  {
    value: "photography",
    category: "photography",
    categoryLabel: "Photography",
    promptText: "professional photography",
    tags: ["photo", "realistic"],
  },
  {
    value: "studio_photography",
    category: "photography",
    categoryLabel: "Photography",
    promptText: "studio photography",
    tags: ["studio", "photo"],
  },
  {
    value: "outdoor_photography",
    category: "photography",
    categoryLabel: "Photography",
    promptText: "outdoor photography",
    tags: ["outdoor", "photo"],
  },
  {
    value: "macro_photography",
    category: "photography",
    categoryLabel: "Photography",
    promptText: "macro photography",
    tags: ["macro", "photo"],
  },
  {
    value: "cinematic_photo",
    category: "photography",
    categoryLabel: "Photography",
    promptText: "cinematic photography",
    tags: ["cinematic", "photo"],
  },
  {
    value: "photomontage",
    category: "photography",
    categoryLabel: "Photography",
    promptText: "photomontage composition",
    tags: ["photo", "montage"],
  },

  // Paper / Craft
  {
    value: "paper_cutout",
    category: "paper_craft",
    categoryLabel: "Paper / Craft",
    promptText: "paper cutout artwork",
    tags: ["paper", "cutout"],
  },
  {
    value: "paper_collage",
    category: "paper_craft",
    categoryLabel: "Paper / Craft",
    promptText: "paper collage artwork",
    tags: ["paper", "collage"],
  },
  {
    value: "mixed_media_collage",
    category: "paper_craft",
    categoryLabel: "Paper / Craft",
    promptText: "mixed-media collage artwork",
    tags: ["mixed-media", "collage"],
  },
  {
    value: "paper_craft",
    category: "paper_craft",
    categoryLabel: "Paper / Craft",
    promptText: "handmade paper craft",
    tags: ["paper", "craft"],
  },
  {
    value: "origami_art",
    category: "paper_craft",
    categoryLabel: "Paper / Craft",
    promptText: "origami-inspired paper artwork",
    tags: ["origami", "paper"],
  },

  // Sculpture / Object
  {
    value: "clay_sculpture",
    category: "sculpture_object",
    categoryLabel: "Sculpture / Object",
    promptText: "handmade clay sculpture",
    tags: ["clay", "sculpture"],
  },
  {
    value: "ceramic_sculpture",
    category: "sculpture_object",
    categoryLabel: "Sculpture / Object",
    promptText: "ceramic sculpture",
    tags: ["ceramic", "sculpture"],
  },
  {
    value: "plasticine_sculpture",
    category: "sculpture_object",
    categoryLabel: "Sculpture / Object",
    promptText: "plasticine sculpture",
    tags: ["plasticine", "sculpture"],
  },
  {
    value: "paper_mache_sculpture",
    category: "sculpture_object",
    categoryLabel: "Sculpture / Object",
    promptText: "papier-mâché sculpture",
    tags: ["papier-mache", "sculpture"],
  },
  {
    value: "handmade_model",
    category: "sculpture_object",
    categoryLabel: "Sculpture / Object",
    promptText: "handmade miniature model",
    tags: ["model", "miniature"],
  },
  {
    value: "collectible_figure",
    category: "sculpture_object",
    categoryLabel: "Sculpture / Object",
    promptText: "collectible figure design",
    tags: ["figure", "collectible"],
  },
  {
    value: "vinyl_toy_model",
    category: "sculpture_object",
    categoryLabel: "Sculpture / Object",
    promptText: "vinyl toy model",
    tags: ["vinyl-toy", "figure"],
  },

  // Textile / Handmade
  {
    value: "fabric_doll",
    category: "textile_handmade",
    categoryLabel: "Textile / Handmade",
    promptText: "fabric doll craftsmanship",
    tags: ["fabric", "doll"],
  },
  {
    value: "felt_craft",
    category: "textile_handmade",
    categoryLabel: "Textile / Handmade",
    promptText: "felt craft artwork",
    tags: ["felt", "craft"],
  },
  {
    value: "plush_toy",
    category: "textile_handmade",
    categoryLabel: "Textile / Handmade",
    promptText: "plush toy design",
    tags: ["plush", "toy"],
  },
  {
    value: "stitched_textile_art",
    category: "textile_handmade",
    categoryLabel: "Textile / Handmade",
    promptText: "stitched textile artwork",
    tags: ["stitched", "textile"],
  },
];

const stylizationLevelOptions = [
  {
    value: "subtle",
    promptText: "subtle stylization, minimal exaggeration",
    tags: ["subtle"],
  },
  {
    value: "controlled",
    promptText: "controlled stylization with moderate exaggeration",
    tags: ["controlled"],
  },
  {
    value: "strong",
    promptText: "strong stylization, notable exaggeration in form",
    tags: ["strong", "exaggerated"],
  },
  {
    value: "extreme",
    promptText: "extreme stylization, highly exaggerated visual identity",
    tags: ["extreme", "exaggerated"],
  },
  {
    value: "abstract",
    promptText:
      "abstract stylization, forms significantly simplified or deconstructed",
    tags: ["abstract", "stylized"],
  },
];

const shapeLanguageOptions = [
  {
    value: "soft_rounded",
    promptText: "soft rounded silhouettes and smooth sculpted forms",
    tags: ["soft", "rounded"],
  },
  {
    value: "geometric",
    promptText: "geometric shape language with simplified structured forms",
    tags: ["geometric", "structured"],
  },
  {
    value: "fluid",
    promptText: "fluid organic forms with graceful continuous curves",
    tags: ["fluid", "organic"],
  },
  {
    value: "blocky",
    promptText:
      "block-built sculptural forms with simplified volumetric masses",
    tags: ["blocky", "sculptural"],
  },
  {
    value: "elongated",
    promptText: "elongated forms, extended proportions and vertical emphasis",
    tags: ["elongated", "stretch"],
  },
  {
    value: "angular",
    promptText: "sharp angular forms with high-contrast edges",
    tags: ["angular", "sharp"],
  },
];

const visualTreatmentOptions = [
  {
    value: "cel_shaded",
    promptText: "clean cel-shaded surfaces with crisp graphic separation",
    tags: ["cel-shaded", "graphic"],
    compatibility: {
      preferredTags: [
        "digital",
        "illustration",
        "vector",
        "3d",
        "render",
        "cgi",
        "game",
        "low-poly",
        "anime",
      ],
      supportedTags: [
        "painting",
        "acrylic",
        "gouache",
        "screen-print",
        "risograph",
        "paper",
        "cutout",
        "figure",
        "vinyl-toy",
      ],
      discouragedTags: [
        "photo",
        "realistic",
        "macro",
        "charcoal",
        "etching",
        "woodcut",
        "linocut",
        "fabric",
        "felt",
        "plush",
        "textile",
      ],
      warningKey:
        "modules.style.fields.visualTreatment.compatibilityWarnings.mediumMismatch",
    },
  },
  {
    value: "flat_graphic",
    promptText: "flat color fields, bold graphic silhouettes, minimal shading",
    tags: ["flat", "graphic"],
    compatibility: {
      preferredTags: [
        "vector",
        "digital",
        "illustration",
        "screen-print",
        "risograph",
        "paper",
        "cutout",
        "collage",
        "pixel-art",
      ],
      supportedTags: [
        "drawing",
        "ink",
        "pen",
        "marker",
        "gouache",
        "acrylic",
        "printmaking",
        "linocut",
        "woodcut",
        "origami",
      ],
      discouragedTags: [
        "photo",
        "realistic",
        "macro",
        "oil",
        "watercolor",
        "charcoal",
        "pastel",
        "ceramic",
        "clay",
        "plasticine",
        "fabric",
        "plush",
      ],
      warningKey:
        "modules.style.fields.visualTreatment.compatibilityWarnings.mediumMismatch",
    },
  },
  {
    value: "ink_watercolor",
    promptText: "messy ink lines, rough watercolor washes, sketchbook texture",
    tags: ["ink", "watercolor", "sketch"],
    compatibility: {
      preferredTags: [
        "watercolor",
        "ink",
        "wash",
        "pen",
        "drawing",
        "illustration",
      ],
      supportedTags: [
        "pencil",
        "colored-pencil",
        "marker",
        "gouache",
        "pastel",
        "paper",
        "collage",
        "mixed-media",
      ],
      discouragedTags: [
        "3d",
        "render",
        "cgi",
        "game",
        "low-poly",
        "pixel-art",
        "photo",
        "realistic",
        "vector",
        "ceramic",
        "clay",
        "vinyl-toy",
        "plush",
      ],
      warningKey:
        "modules.style.fields.visualTreatment.compatibilityWarnings.mediumMismatch",
    },
  },
  {
    value: "halftone_comic",
    promptText:
      "bold comic-book treatment with halftone shading and clean black outlines",
    tags: ["comic", "halftone"],
    compatibility: {
      preferredTags: [
        "digital",
        "illustration",
        "ink",
        "pen",
        "screen-print",
        "risograph",
        "printmaking",
      ],
      supportedTags: [
        "vector",
        "marker",
        "gouache",
        "acrylic",
        "paper",
        "collage",
        "mixed-media",
        "pixel-art",
      ],
      discouragedTags: [
        "photo",
        "realistic",
        "macro",
        "oil",
        "watercolor",
        "charcoal",
        "pastel",
        "clay",
        "ceramic",
        "fabric",
        "felt",
        "plush",
      ],
      warningKey:
        "modules.style.fields.visualTreatment.compatibilityWarnings.mediumMismatch",
    },
  },
  {
    value: "hand_painted",
    promptText:
      "visible hand-painted surface variation and expressive brush marks",
    tags: ["painted", "brush"],
    compatibility: {
      preferredTags: [
        "painting",
        "oil",
        "acrylic",
        "gouache",
        "watercolor",
        "digital",
        "clay",
        "ceramic",
        "plasticine",
        "papier-mache",
      ],
      supportedTags: [
        "illustration",
        "marker",
        "pastel",
        "mixed-media",
        "paper",
        "craft",
        "model",
        "miniature",
        "figure",
        "fabric",
        "felt",
      ],
      discouragedTags: [
        "photo",
        "realistic",
        "macro",
        "vector",
        "pixel-art",
        "low-poly",
        "linocut",
        "woodcut",
        "etching",
      ],
      warningKey:
        "modules.style.fields.visualTreatment.compatibilityWarnings.mediumMismatch",
    },
  },
  {
    value: "paper_cutout",
    promptText: "flat cut-paper construction with simple layered shapes",
    tags: ["paper", "cutout", "flat"],
    compatibility: {
      preferredTags: [
        "paper",
        "cutout",
        "collage",
        "craft",
        "origami",
        "mixed-media",
      ],
      supportedTags: [
        "vector",
        "digital",
        "illustration",
        "screen-print",
        "risograph",
        "felt",
        "fabric",
      ],
      discouragedTags: [
        "photo",
        "realistic",
        "macro",
        "3d",
        "render",
        "cgi",
        "oil",
        "watercolor",
        "charcoal",
        "clay",
        "ceramic",
        "vinyl-toy",
      ],
      warningKey:
        "modules.style.fields.visualTreatment.compatibilityWarnings.mediumMismatch",
    },
  },
  {
    value: "minimalist",
    promptText:
      "minimalist visual treatment, simple forms and restrained detail",
    tags: ["minimalist"],
    compatibility: {
      preferredTags: [
        "vector",
        "digital",
        "illustration",
        "photo",
        "studio",
        "paper",
        "origami",
        "ceramic",
        "model",
      ],
      supportedTags: [
        "3d",
        "render",
        "cgi",
        "drawing",
        "ink",
        "pen",
        "screen-print",
        "risograph",
        "clay",
        "figure",
        "vinyl-toy",
      ],
      discouragedTags: [
        "mixed-media",
        "collage",
        "charcoal",
        "pastel",
        "woodcut",
        "etching",
        "fabric",
        "stitched",
        "textile",
      ],
      warningKey:
        "modules.style.fields.visualTreatment.compatibilityWarnings.mediumMismatch",
    },
  },
  {
    value: "textured",
    promptText: "rich surface textures and tactile visual impression",
    tags: ["textured", "tactile"],
    compatibility: {
      preferredTags: [
        "painting",
        "oil",
        "acrylic",
        "gouache",
        "charcoal",
        "pastel",
        "printmaking",
        "linocut",
        "woodcut",
        "etching",
        "paper",
        "collage",
        "mixed-media",
        "clay",
        "ceramic",
        "plasticine",
        "papier-mache",
        "fabric",
        "felt",
        "plush",
        "stitched",
        "textile",
      ],
      supportedTags: [
        "digital",
        "illustration",
        "3d",
        "render",
        "cgi",
        "model",
        "miniature",
        "figure",
        "vinyl-toy",
      ],
      discouragedTags: ["vector", "pixel-art", "photo", "studio", "macro"],
      warningKey:
        "modules.style.fields.visualTreatment.compatibilityWarnings.mediumMismatch",
    },
  },
];

const finishOptions = [
  {
    value: "clean",
    promptText: "clean polished aesthetic",
    tags: ["clean", "polished"],
    compatibility: {
      preferredTags: [
        "digital",
        "illustration",
        "vector",
        "3d",
        "render",
        "cgi",
        "game",
        "low-poly",
        "photo",
        "studio",
        "ceramic",
        "figure",
        "vinyl-toy",
      ],
      supportedTags: [
        "painting",
        "acrylic",
        "gouache",
        "paper",
        "craft",
        "origami",
        "model",
        "miniature",
        "collectible",
      ],
      discouragedTags: [
        "charcoal",
        "pastel",
        "woodcut",
        "linocut",
        "etching",
        "fabric",
        "felt",
        "plush",
        "stitched",
        "textile",
      ],
      warningKey:
        "modules.style.fields.finish.compatibilityWarnings.mediumMismatch",
    },
  },
  {
    value: "premium",
    promptText: "luxury visual style, premium polished aesthetic",
    tags: ["premium", "luxury"],
    compatibility: {
      preferredTags: [
        "3d",
        "render",
        "cgi",
        "game",
        "photo",
        "studio",
        "cinematic",
        "ceramic",
        "model",
        "miniature",
        "figure",
        "collectible",
        "vinyl-toy",
      ],
      supportedTags: [
        "digital",
        "illustration",
        "vector",
        "painting",
        "oil",
        "acrylic",
        "paper",
        "origami",
      ],
      discouragedTags: [
        "pencil",
        "charcoal",
        "pastel",
        "ink",
        "woodcut",
        "linocut",
        "etching",
        "fabric",
        "felt",
        "plush",
        "stitched",
        "textile",
      ],
      warningKey:
        "modules.style.fields.finish.compatibilityWarnings.mediumMismatch",
    },
  },
  {
    value: "handcrafted",
    promptText: "handcrafted artistic feel with tactile visual character",
    tags: ["handcrafted", "tactile"],
    compatibility: {
      preferredTags: [
        "paper",
        "cutout",
        "collage",
        "mixed-media",
        "craft",
        "origami",
        "clay",
        "ceramic",
        "plasticine",
        "papier-mache",
        "model",
        "miniature",
        "fabric",
        "felt",
        "plush",
        "stitched",
        "textile",
      ],
      supportedTags: [
        "drawing",
        "pencil",
        "colored-pencil",
        "charcoal",
        "ink",
        "pastel",
        "painting",
        "watercolor",
        "gouache",
        "oil",
        "acrylic",
        "printmaking",
      ],
      discouragedTags: [
        "photo",
        "realistic",
        "studio",
        "macro",
        "vector",
        "cgi",
        "game",
        "low-poly",
        "pixel-art",
      ],
      warningKey:
        "modules.style.fields.finish.compatibilityWarnings.mediumMismatch",
    },
  },
  {
    value: "graphic",
    promptText: "bold graphic visual treatment with clear stylized readability",
    tags: ["graphic", "bold"],
    compatibility: {
      preferredTags: [
        "vector",
        "digital",
        "illustration",
        "pixel-art",
        "ink",
        "pen",
        "marker",
        "screen-print",
        "risograph",
        "linocut",
        "woodcut",
        "paper",
        "cutout",
      ],
      supportedTags: [
        "3d",
        "render",
        "low-poly",
        "gouache",
        "acrylic",
        "collage",
        "mixed-media",
        "origami",
      ],
      discouragedTags: [
        "photo",
        "realistic",
        "macro",
        "oil",
        "watercolor",
        "charcoal",
        "pastel",
        "clay",
        "ceramic",
        "fabric",
        "plush",
      ],
      warningKey:
        "modules.style.fields.finish.compatibilityWarnings.mediumMismatch",
    },
  },
  {
    value: "rough",
    promptText: "rough, sketchy or imperfect finish for artistic character",
    tags: ["rough", "sketchy"],
    compatibility: {
      preferredTags: [
        "pencil",
        "colored-pencil",
        "charcoal",
        "ink",
        "pen",
        "pastel",
        "watercolor",
        "gouache",
        "oil",
        "printmaking",
        "linocut",
        "woodcut",
        "etching",
        "paper",
        "collage",
        "mixed-media",
        "papier-mache",
        "fabric",
        "felt",
        "stitched",
        "textile",
      ],
      supportedTags: [
        "digital",
        "illustration",
        "acrylic",
        "clay",
        "ceramic",
        "plasticine",
        "model",
        "miniature",
      ],
      discouragedTags: [
        "photo",
        "studio",
        "macro",
        "vector",
        "cgi",
        "game",
        "vinyl-toy",
        "collectible",
      ],
      warningKey:
        "modules.style.fields.finish.compatibilityWarnings.mediumMismatch",
    },
  },
  {
    value: "matte",
    promptText: "soft matte finish without reflections",
    tags: ["matte"],
    compatibility: {
      preferredTags: [
        "drawing",
        "pencil",
        "colored-pencil",
        "charcoal",
        "pastel",
        "watercolor",
        "gouache",
        "paper",
        "cutout",
        "collage",
        "craft",
        "origami",
        "clay",
        "plasticine",
        "papier-mache",
        "fabric",
        "felt",
        "plush",
        "stitched",
        "textile",
      ],
      supportedTags: [
        "digital",
        "illustration",
        "vector",
        "3d",
        "render",
        "acrylic",
        "ceramic",
        "model",
        "miniature",
        "figure",
      ],
      discouragedTags: [
        "photo",
        "studio",
        "macro",
        "cinematic",
        "oil",
        "cgi",
        "vinyl-toy",
      ],
      warningKey:
        "modules.style.fields.finish.compatibilityWarnings.mediumMismatch",
    },
  },
  {
    value: "glossy",
    promptText: "high gloss reflective surface for polished look",
    tags: ["glossy"],
    compatibility: {
      preferredTags: [
        "3d",
        "render",
        "cgi",
        "game",
        "ceramic",
        "plasticine",
        "figure",
        "collectible",
        "vinyl-toy",
        "photo",
        "studio",
        "macro",
      ],
      supportedTags: [
        "digital",
        "illustration",
        "oil",
        "acrylic",
        "model",
        "miniature",
      ],
      discouragedTags: [
        "pencil",
        "colored-pencil",
        "charcoal",
        "ink",
        "pen",
        "pastel",
        "watercolor",
        "screen-print",
        "risograph",
        "linocut",
        "woodcut",
        "etching",
        "paper",
        "cutout",
        "collage",
        "origami",
        "fabric",
        "felt",
        "plush",
        "stitched",
        "textile",
      ],
      warningKey:
        "modules.style.fields.finish.compatibilityWarnings.mediumMismatch",
    },
  },
];

export const StyleModule = {
  key: "style",
  icon: "magicpen",

  groups: {
    core: {
      id: "core",
      order: 10,
      defaultOpen: false,
    },
    modifiers: {
      id: "modifiers",
      order: 20,
      defaultOpen: true,
    },
    advanced: {
      id: "advanced",
      order: 30,
      defaultOpen: false,
    },
    override: {
      id: "override",
      order: 40,
      defaultOpen: false,
    },
  },

  fields: {
    preset: {
      id: "preset",
      type: "select",
      default: "",
      group: "core",
      order: 10,
      options: stylePresetOptions,
      ui: {
        component: "select",
        searchable: true,
        clearable: true,
        width: "full",
      },
    },

    medium: {
      id: "medium",
      type: "select",
      default: "",
      group: "core",
      order: 20,
      options: mediumOptions,
      ui: {
        component: "select",
        optionLayout: "categorized",
        clearable: true,
        width: "full",
      },
    },

    stylizationLevel: {
      id: "stylizationLevel",
      type: "select",
      default: "controlled",
      group: "modifiers",
      order: 10,
      options: stylizationLevelOptions,
      ui: {
        component: "segmented",
        clearable: false,
        width: "half",
      },
    },

    shapeLanguage: {
      id: "shapeLanguage",
      type: "select",
      default: "",
      group: "modifiers",
      order: 20,
      options: shapeLanguageOptions,
      ui: {
        component: "select",
        clearable: true,
        width: "half",
      },
    },

    visualTreatment: {
      id: "visualTreatment",
      type: "select",
      default: "",
      group: "modifiers",
      order: 25,
      options: visualTreatmentOptions,
      ui: {
        component: "select",
        clearable: true,
        width: "half",
        compatibility: {
          dependsOn: "medium",
          mode: "sort-and-hint",
        },
      },
    },

    finish: {
      id: "finish",
      type: "select",
      default: "",
      group: "modifiers",
      order: 30,
      options: finishOptions,
      ui: {
        component: "select",
        clearable: true,
        width: "half",
        compatibility: {
          dependsOn: "medium",
          mode: "sort-and-hint",
        },
      },
    },

    extraDetails: {
      id: "extraDetails",
      type: "textarea",
      default: "",
      group: "advanced",
      order: 10,
      ui: {
        component: "textarea",
        rows: 3,
        width: "full",
      },
    },

    customText: {
      id: "customText",
      type: "textarea",
      default: "",
      group: "override",
      order: 10,
      isOverride: true,
      ui: {
        component: "textarea",
        rows: 4,
        width: "full",
      },
    },
  },

  presets: {
    soft_3d_cartoon: {
      id: "soft_3d_cartoon",
      order: 10,
      values: {
        preset: "3d_cartoon",
        medium: "three_d_render",
        stylizationLevel: "strong",
        shapeLanguage: "soft_rounded",
        visualTreatment: "cel_shaded",
        finish: "clean",
      },
    },

    premium_vinyl_character: {
      id: "premium_vinyl_character",
      order: 20,
      values: {
        preset: "vinyl_toy",
        medium: "three_d_render",
        stylizationLevel: "controlled",
        shapeLanguage: "soft_rounded",
        visualTreatment: "",
        finish: "premium",
      },
    },

    handmade_clay_artwork: {
      id: "handmade_clay_artwork",
      order: 30,
      values: {
        preset: "clay_sculpture",
        medium: "three_d_render",
        stylizationLevel: "controlled",
        shapeLanguage: "fluid",
        visualTreatment: "hand_painted",
        finish: "handcrafted",
      },
    },

    cinematic_realistic_image: {
      id: "cinematic_realistic_image",
      order: 40,
      values: {
        preset: "cinematic_realism",
        medium: "photo_real",
        stylizationLevel: "subtle",
        shapeLanguage: "",
        visualTreatment: "",
        finish: "clean",
      },
    },

    geometric_editorial_portrait: {
      id: "geometric_editorial_portrait",
      order: 50,
      values: {
        preset: "geometric_editorial",
        medium: "digital_illustration",
        stylizationLevel: "strong",
        shapeLanguage: "geometric",
        visualTreatment: "flat_graphic",
        finish: "graphic",
      },
    },

    retro_comic_pop_art: {
      id: "retro_comic_pop_art",
      order: 60,
      values: {
        preset: "retro_comic",
        medium: "digital_illustration",
        stylizationLevel: "strong",
        shapeLanguage: "geometric",
        visualTreatment: "halftone_comic",
        finish: "graphic",
      },
    },

    messy_fashion_caricature: {
      id: "messy_fashion_caricature",
      order: 70,
      values: {
        preset: "fashion_caricature_sketch",
        medium: "digital_illustration",
        stylizationLevel: "extreme",
        shapeLanguage: "fluid",
        visualTreatment: "ink_watercolor",
        finish: "handcrafted",
      },
    },

    primitive_cut_paper_portrait: {
      id: "primitive_cut_paper_portrait",
      order: 80,
      values: {
        preset: "primitive_cut_paper",
        medium: "digital_illustration",
        stylizationLevel: "extreme",
        shapeLanguage: "geometric",
        visualTreatment: "paper_cutout",
        finish: "graphic",
      },
    },

    angular_2d_animation: {
      id: "angular_2d_animation",
      order: 90,
      values: {
        preset: "angular_animation",
        medium: "digital_illustration",
        stylizationLevel: "strong",
        shapeLanguage: "geometric",
        visualTreatment: "flat_graphic",
        finish: "graphic",
      },
    },

    naive_childlike_artwork: {
      id: "naive_childlike_artwork",
      order: 100,
      values: {
        preset: "childlike_drawing",
        medium: "digital_illustration",
        stylizationLevel: "extreme",
        shapeLanguage: "",
        visualTreatment: "hand_painted",
        finish: "handcrafted",
      },
    },

    watercolor_editorial: {
      id: "watercolor_editorial",
      order: 110,
      values: {
        preset: "watercolor_editorial",
        medium: "watercolor_painting",
        stylizationLevel: "controlled",
        shapeLanguage: "fluid",
        visualTreatment: "ink_watercolor",
        finish: "clean",
      },
    },

    crafted_paper_collage: {
      id: "crafted_paper_collage",
      order: 120,
      values: {
        preset: "crafted_paper_collage",
        medium: "paper_collage",
        stylizationLevel: "controlled",
        shapeLanguage: "blocky",
        visualTreatment: "paper_cutout",
        finish: "handcrafted",
      },
    },

    low_poly_character: {
      id: "low_poly_character",
      order: 130,
      values: {
        preset: "low_poly_character",
        medium: "low_poly_render",
        stylizationLevel: "strong",
        shapeLanguage: "geometric",
        visualTreatment: "minimalist",
        finish: "clean",
      },
    },

    pixel_art_game_character: {
      id: "pixel_art_game_character",
      order: 140,
      values: {
        preset: "pixel_art_game_character",
        medium: "pixel_art_digital",
        stylizationLevel: "strong",
        shapeLanguage: "blocky",
        visualTreatment: "minimalist",
        finish: "graphic",
      },
    },

    risograph_poster_art: {
      id: "risograph_poster_art",
      order: 150,
      values: {
        preset: "risograph_poster_art",
        medium: "risograph_print",
        stylizationLevel: "controlled",
        shapeLanguage: "geometric",
        visualTreatment: "flat_graphic",
        finish: "graphic",
      },
    },

    ink_character_sketch: {
      id: "ink_character_sketch",
      order: 160,
      values: {
        preset: "ink_character_sketch",
        medium: "ink_drawing",
        stylizationLevel: "controlled",
        shapeLanguage: "fluid",
        visualTreatment: "ink_watercolor",
        finish: "rough",
      },
    },

    cinematic_cgi_character: {
      id: "cinematic_cgi_character",
      order: 170,
      values: {
        preset: "cinematic_cgi_character",
        medium: "cgi",
        stylizationLevel: "controlled",
        shapeLanguage: "soft_rounded",
        visualTreatment: "hand_painted",
        finish: "premium",
      },
    },

    studio_photo_realism: {
      id: "studio_photo_realism",
      order: 180,
      values: {
        preset: "studio_photo_realism",
        medium: "studio_photography",
        stylizationLevel: "subtle",
        shapeLanguage: "fluid",
        visualTreatment: "minimalist",
        finish: "clean",
      },
    },

    papier_mache_character: {
      id: "papier_mache_character",
      order: 190,
      values: {
        preset: "papier_mache_character",
        medium: "paper_mache_sculpture",
        stylizationLevel: "extreme",
        shapeLanguage: "angular",
        visualTreatment: "minimalist",
        finish: "handcrafted",
      },
    },

    plush_toy_character: {
      id: "plush_toy_character",
      order: 200,
      values: {
        preset: "plush_toy_character",
        medium: "plush_toy",
        stylizationLevel: "strong",
        shapeLanguage: "soft_rounded",
        visualTreatment: "minimalist",
        finish: "handcrafted",
      },
    },

    woodcut_editorial: {
      id: "woodcut_editorial",
      order: 210,
      values: {
        preset: "woodcut_editorial",
        medium: "woodcut_print",
        stylizationLevel: "strong",
        shapeLanguage: "angular",
        visualTreatment: "flat_graphic",
        finish: "rough",
      },
    },

    marker_concept_art: {
      id: "marker_concept_art",
      order: 220,
      values: {
        preset: "marker_concept_art",
        medium: "marker_render",
        stylizationLevel: "controlled",
        shapeLanguage: "geometric",
        visualTreatment: "hand_painted",
        finish: "clean",
      },
    },
  },

  compile: {
    separator: ", ",
    removeDuplicates: true,
    ignoreEmpty: true,
    overrideField: "customText",
  },
} satisfies PromptKeyModule;
