import type { PromptKeyModule } from "./types";

const materialOptions = [
  // Vinyl / Plastic
  {
    value: "vinyl",
    category: "vinyl_plastic",
    categoryLabel: "Vinyl / Plastic",
    categoryLabelKey: "modules.texture.categories.vinyl_plastic",
    promptText: "vinyl material",
    tags: [
      "vinyl",
      "plastic",
      "synthetic",
      "rigid",
      "opaque",
      "smooth-friendly",
      "toy-friendly",
    ],
  },
  {
    value: "pvc",
    category: "vinyl_plastic",
    categoryLabel: "Vinyl / Plastic",
    categoryLabelKey: "modules.texture.categories.vinyl_plastic",
    promptText: "PVC plastic material",
    tags: [
      "pvc",
      "plastic",
      "synthetic",
      "rigid",
      "opaque",
      "smooth-friendly",
      "industrial",
    ],
  },
  {
    value: "molded_plastic",
    category: "vinyl_plastic",
    categoryLabel: "Vinyl / Plastic",
    categoryLabelKey: "modules.texture.categories.vinyl_plastic",
    promptText: "molded plastic material",
    tags: [
      "plastic",
      "synthetic",
      "rigid",
      "opaque",
      "smooth-friendly",
      "molded",
    ],
  },
  {
    value: "acrylic_plastic",
    category: "vinyl_plastic",
    categoryLabel: "Vinyl / Plastic",
    categoryLabelKey: "modules.texture.categories.vinyl_plastic",
    promptText: "acrylic plastic material",
    tags: [
      "acrylic",
      "plastic",
      "synthetic",
      "rigid",
      "transparent-friendly",
      "translucent-friendly",
      "gloss-friendly",
    ],
  },
  {
    value: "resin",
    category: "vinyl_plastic",
    categoryLabel: "Vinyl / Plastic",
    categoryLabelKey: "modules.texture.categories.vinyl_plastic",
    promptText: "resin material",
    tags: [
      "resin",
      "plastic",
      "synthetic",
      "rigid",
      "transparent-friendly",
      "translucent-friendly",
      "gloss-friendly",
      "sculptural",
    ],
  },
  {
    value: "silicone",
    category: "vinyl_plastic",
    categoryLabel: "Vinyl / Plastic",
    categoryLabelKey: "modules.texture.categories.vinyl_plastic",
    promptText: "silicone material",
    tags: [
      "silicone",
      "synthetic",
      "soft",
      "flexible",
      "rubbery",
      "matte-friendly",
      "translucent-friendly",
    ],
  },

  // Clay / Ceramic
  {
    value: "clay",
    category: "clay_ceramic",
    categoryLabel: "Clay / Ceramic",
    categoryLabelKey: "modules.texture.categories.clay_ceramic",
    promptText: "clay material",
    tags: [
      "clay",
      "earth",
      "organic",
      "rigid",
      "opaque",
      "porous",
      "grainable",
      "handmade-friendly",
    ],
  },
  {
    value: "terracotta",
    category: "clay_ceramic",
    categoryLabel: "Clay / Ceramic",
    categoryLabelKey: "modules.texture.categories.clay_ceramic",
    promptText: "terracotta clay material",
    tags: [
      "terracotta",
      "clay",
      "ceramic",
      "earth",
      "rigid",
      "opaque",
      "porous",
      "grainable",
      "handmade-friendly",
    ],
  },
  {
    value: "porcelain",
    category: "clay_ceramic",
    categoryLabel: "Clay / Ceramic",
    categoryLabelKey: "modules.texture.categories.clay_ceramic",
    promptText: "porcelain ceramic material",
    tags: [
      "porcelain",
      "ceramic",
      "rigid",
      "opaque",
      "fragile",
      "smooth-friendly",
      "gloss-friendly",
    ],
  },
  {
    value: "stoneware",
    category: "clay_ceramic",
    categoryLabel: "Clay / Ceramic",
    categoryLabelKey: "modules.texture.categories.clay_ceramic",
    promptText: "stoneware ceramic material",
    tags: [
      "stoneware",
      "ceramic",
      "clay",
      "rigid",
      "opaque",
      "porous",
      "grainable",
      "handmade-friendly",
    ],
  },
  {
    value: "earthenware",
    category: "clay_ceramic",
    categoryLabel: "Clay / Ceramic",
    categoryLabelKey: "modules.texture.categories.clay_ceramic",
    promptText: "earthenware ceramic material",
    tags: [
      "earthenware",
      "ceramic",
      "clay",
      "earth",
      "rigid",
      "opaque",
      "porous",
      "grainable",
      "handmade-friendly",
    ],
  },

  // Metal
  {
    value: "metal",
    category: "metal",
    categoryLabel: "Metal",
    categoryLabelKey: "modules.texture.categories.metal",
    promptText: "metal material",
    tags: [
      "metal",
      "rigid",
      "opaque",
      "reflective",
      "industrial",
      "scratch-friendly",
      "corrosion-friendly",
    ],
  },
  {
    value: "steel",
    category: "metal",
    categoryLabel: "Metal",
    categoryLabelKey: "modules.texture.categories.metal",
    promptText: "steel material",
    tags: [
      "steel",
      "metal",
      "rigid",
      "opaque",
      "reflective",
      "industrial",
      "scratch-friendly",
      "corrosion-friendly",
    ],
  },
  {
    value: "stainless_steel",
    category: "metal",
    categoryLabel: "Metal",
    categoryLabelKey: "modules.texture.categories.metal",
    promptText: "stainless steel material",
    tags: [
      "stainless-steel",
      "metal",
      "rigid",
      "opaque",
      "reflective",
      "industrial",
      "scratch-friendly",
      "clean-friendly",
    ],
  },
  {
    value: "iron",
    category: "metal",
    categoryLabel: "Metal",
    categoryLabelKey: "modules.texture.categories.metal",
    promptText: "iron material",
    tags: [
      "iron",
      "metal",
      "rigid",
      "opaque",
      "industrial",
      "scratch-friendly",
      "corrosion-friendly",
      "rust-friendly",
    ],
  },
  {
    value: "aluminum",
    category: "metal",
    categoryLabel: "Metal",
    categoryLabelKey: "modules.texture.categories.metal",
    promptText: "aluminum material",
    tags: [
      "aluminum",
      "metal",
      "rigid",
      "opaque",
      "reflective",
      "industrial",
      "scratch-friendly",
      "brushed-friendly",
    ],
  },
  {
    value: "copper",
    category: "metal",
    categoryLabel: "Metal",
    categoryLabelKey: "modules.texture.categories.metal",
    promptText: "copper material",
    tags: [
      "copper",
      "metal",
      "rigid",
      "opaque",
      "reflective",
      "oxidation-friendly",
      "patina-friendly",
      "corrosion-friendly",
    ],
  },
  {
    value: "brass",
    category: "metal",
    categoryLabel: "Metal",
    categoryLabelKey: "modules.texture.categories.metal",
    promptText: "brass material",
    tags: [
      "brass",
      "metal",
      "rigid",
      "opaque",
      "reflective",
      "oxidation-friendly",
      "patina-friendly",
      "aged-friendly",
    ],
  },
  {
    value: "bronze",
    category: "metal",
    categoryLabel: "Metal",
    categoryLabelKey: "modules.texture.categories.metal",
    promptText: "bronze material",
    tags: [
      "bronze",
      "metal",
      "rigid",
      "opaque",
      "reflective",
      "oxidation-friendly",
      "patina-friendly",
      "aged-friendly",
    ],
  },
  {
    value: "silver",
    category: "metal",
    categoryLabel: "Metal",
    categoryLabelKey: "modules.texture.categories.metal",
    promptText: "silver material",
    tags: [
      "silver",
      "metal",
      "rigid",
      "opaque",
      "reflective",
      "gloss-friendly",
      "scratch-friendly",
    ],
  },
  {
    value: "gold",
    category: "metal",
    categoryLabel: "Metal",
    categoryLabelKey: "modules.texture.categories.metal",
    promptText: "gold material",
    tags: [
      "gold",
      "metal",
      "rigid",
      "opaque",
      "reflective",
      "gloss-friendly",
      "luxury-friendly",
    ],
  },
  {
    value: "titanium",
    category: "metal",
    categoryLabel: "Metal",
    categoryLabelKey: "modules.texture.categories.metal",
    promptText: "titanium material",
    tags: [
      "titanium",
      "metal",
      "rigid",
      "opaque",
      "reflective",
      "industrial",
      "scratch-friendly",
    ],
  },
  {
    value: "chrome",
    category: "metal",
    categoryLabel: "Metal",
    categoryLabelKey: "modules.texture.categories.metal",
    promptText: "chrome material",
    tags: [
      "chrome",
      "metal",
      "rigid",
      "opaque",
      "mirror-friendly",
      "gloss-friendly",
      "reflective",
    ],
  },

  // Wood
  {
    value: "oak",
    category: "wood",
    categoryLabel: "Wood",
    categoryLabelKey: "modules.texture.categories.wood",
    promptText: "oak wood material",
    tags: [
      "oak",
      "wood",
      "organic",
      "rigid",
      "opaque",
      "grainable",
      "porous",
      "carvable",
    ],
  },
  {
    value: "walnut",
    category: "wood",
    categoryLabel: "Wood",
    categoryLabelKey: "modules.texture.categories.wood",
    promptText: "walnut wood material",
    tags: [
      "walnut",
      "wood",
      "organic",
      "rigid",
      "opaque",
      "grainable",
      "porous",
      "carvable",
    ],
  },
  {
    value: "maple",
    category: "wood",
    categoryLabel: "Wood",
    categoryLabelKey: "modules.texture.categories.wood",
    promptText: "maple wood material",
    tags: [
      "maple",
      "wood",
      "organic",
      "rigid",
      "opaque",
      "grainable",
      "smooth-friendly",
      "carvable",
    ],
  },
  {
    value: "pine",
    category: "wood",
    categoryLabel: "Wood",
    categoryLabelKey: "modules.texture.categories.wood",
    promptText: "pine wood material",
    tags: [
      "pine",
      "wood",
      "organic",
      "rigid",
      "opaque",
      "grainable",
      "soft-wood",
      "carvable",
    ],
  },
  {
    value: "birch",
    category: "wood",
    categoryLabel: "Wood",
    categoryLabelKey: "modules.texture.categories.wood",
    promptText: "birch wood material",
    tags: [
      "birch",
      "wood",
      "organic",
      "rigid",
      "opaque",
      "grainable",
      "smooth-friendly",
      "carvable",
    ],
  },
  {
    value: "cedar",
    category: "wood",
    categoryLabel: "Wood",
    categoryLabelKey: "modules.texture.categories.wood",
    promptText: "cedar wood material",
    tags: [
      "cedar",
      "wood",
      "organic",
      "rigid",
      "opaque",
      "grainable",
      "porous",
      "carvable",
    ],
  },
  {
    value: "mahogany",
    category: "wood",
    categoryLabel: "Wood",
    categoryLabelKey: "modules.texture.categories.wood",
    promptText: "mahogany wood material",
    tags: [
      "mahogany",
      "wood",
      "organic",
      "rigid",
      "opaque",
      "grainable",
      "polish-friendly",
      "luxury-friendly",
    ],
  },
  {
    value: "bamboo",
    category: "wood",
    categoryLabel: "Wood",
    categoryLabelKey: "modules.texture.categories.wood",
    promptText: "bamboo material",
    tags: [
      "bamboo",
      "wood",
      "organic",
      "rigid",
      "opaque",
      "fibrous",
      "grainable",
      "natural",
    ],
  },

  // Stone / Mineral
  {
    value: "marble",
    category: "stone_mineral",
    categoryLabel: "Stone / Mineral",
    categoryLabelKey: "modules.texture.categories.stone_mineral",
    promptText: "marble stone material",
    tags: [
      "marble",
      "stone",
      "mineral",
      "rigid",
      "opaque",
      "polish-friendly",
      "vein-friendly",
      "luxury-friendly",
    ],
  },
  {
    value: "granite",
    category: "stone_mineral",
    categoryLabel: "Stone / Mineral",
    categoryLabelKey: "modules.texture.categories.stone_mineral",
    promptText: "granite stone material",
    tags: [
      "granite",
      "stone",
      "mineral",
      "rigid",
      "opaque",
      "grainable",
      "speckled-friendly",
      "polish-friendly",
    ],
  },
  {
    value: "limestone",
    category: "stone_mineral",
    categoryLabel: "Stone / Mineral",
    categoryLabelKey: "modules.texture.categories.stone_mineral",
    promptText: "limestone material",
    tags: [
      "limestone",
      "stone",
      "mineral",
      "rigid",
      "opaque",
      "porous",
      "grainable",
      "weathered-friendly",
    ],
  },
  {
    value: "sandstone",
    category: "stone_mineral",
    categoryLabel: "Stone / Mineral",
    categoryLabelKey: "modules.texture.categories.stone_mineral",
    promptText: "sandstone material",
    tags: [
      "sandstone",
      "stone",
      "mineral",
      "rigid",
      "opaque",
      "porous",
      "grainable",
      "rough-friendly",
    ],
  },
  {
    value: "slate",
    category: "stone_mineral",
    categoryLabel: "Stone / Mineral",
    categoryLabelKey: "modules.texture.categories.stone_mineral",
    promptText: "slate stone material",
    tags: [
      "slate",
      "stone",
      "mineral",
      "rigid",
      "opaque",
      "layered",
      "matte-friendly",
      "engrave-friendly",
    ],
  },
  {
    value: "concrete",
    category: "stone_mineral",
    categoryLabel: "Stone / Mineral",
    categoryLabelKey: "modules.texture.categories.stone_mineral",
    promptText: "concrete material",
    tags: [
      "concrete",
      "stone",
      "mineral",
      "industrial",
      "rigid",
      "opaque",
      "porous",
      "grainable",
      "weathered-friendly",
    ],
  },

  // Glass / Crystal
  {
    value: "glass",
    category: "glass_crystal",
    categoryLabel: "Glass / Crystal",
    categoryLabelKey: "modules.texture.categories.glass_crystal",
    promptText: "glass material",
    tags: [
      "glass",
      "rigid",
      "fragile",
      "transparent",
      "reflective",
      "smooth-friendly",
      "gloss-friendly",
    ],
  },
  {
    value: "frosted_glass",
    category: "glass_crystal",
    categoryLabel: "Glass / Crystal",
    categoryLabelKey: "modules.texture.categories.glass_crystal",
    promptText: "frosted glass material",
    tags: [
      "glass",
      "frosted",
      "rigid",
      "fragile",
      "translucent",
      "diffused",
      "smooth-friendly",
    ],
  },
  {
    value: "stained_glass",
    category: "glass_crystal",
    categoryLabel: "Glass / Crystal",
    categoryLabelKey: "modules.texture.categories.glass_crystal",
    promptText: "stained glass material",
    tags: [
      "glass",
      "stained",
      "rigid",
      "fragile",
      "transparent",
      "colored",
      "gloss-friendly",
    ],
  },
  {
    value: "crystal",
    category: "glass_crystal",
    categoryLabel: "Glass / Crystal",
    categoryLabelKey: "modules.texture.categories.glass_crystal",
    promptText: "crystal material",
    tags: [
      "crystal",
      "glass",
      "rigid",
      "fragile",
      "transparent",
      "reflective",
      "gloss-friendly",
      "faceted-friendly",
    ],
  },
  {
    value: "quartz",
    category: "glass_crystal",
    categoryLabel: "Glass / Crystal",
    categoryLabelKey: "modules.texture.categories.glass_crystal",
    promptText: "quartz crystal material",
    tags: [
      "quartz",
      "crystal",
      "mineral",
      "rigid",
      "fragile",
      "translucent",
      "grainable",
      "faceted-friendly",
    ],
  },

  // Fabric / Textile
  {
    value: "cotton",
    category: "fabric_textile",
    categoryLabel: "Fabric / Textile",
    categoryLabelKey: "modules.texture.categories.fabric_textile",
    promptText: "cotton fabric material",
    tags: [
      "cotton",
      "fabric",
      "textile",
      "soft",
      "flexible",
      "woven",
      "matte-friendly",
      "wrinkle-friendly",
    ],
  },
  {
    value: "linen",
    category: "fabric_textile",
    categoryLabel: "Fabric / Textile",
    categoryLabelKey: "modules.texture.categories.fabric_textile",
    promptText: "linen fabric material",
    tags: [
      "linen",
      "fabric",
      "textile",
      "soft",
      "flexible",
      "woven",
      "fibrous",
      "wrinkle-friendly",
    ],
  },
  {
    value: "silk",
    category: "fabric_textile",
    categoryLabel: "Fabric / Textile",
    categoryLabelKey: "modules.texture.categories.fabric_textile",
    promptText: "silk fabric material",
    tags: [
      "silk",
      "fabric",
      "textile",
      "soft",
      "flexible",
      "smooth-friendly",
      "satin-friendly",
      "gloss-friendly",
    ],
  },
  {
    value: "velvet",
    category: "fabric_textile",
    categoryLabel: "Fabric / Textile",
    categoryLabelKey: "modules.texture.categories.fabric_textile",
    promptText: "velvet fabric material",
    tags: [
      "velvet",
      "fabric",
      "textile",
      "soft",
      "flexible",
      "velvety-friendly",
      "matte-friendly",
      "luxury-friendly",
    ],
  },
  {
    value: "wool",
    category: "fabric_textile",
    categoryLabel: "Fabric / Textile",
    categoryLabelKey: "modules.texture.categories.fabric_textile",
    promptText: "wool fabric material",
    tags: [
      "wool",
      "fabric",
      "textile",
      "soft",
      "flexible",
      "fibrous",
      "woven",
      "matte-friendly",
    ],
  },
  {
    value: "denim",
    category: "fabric_textile",
    categoryLabel: "Fabric / Textile",
    categoryLabelKey: "modules.texture.categories.fabric_textile",
    promptText: "denim fabric material",
    tags: [
      "denim",
      "fabric",
      "textile",
      "soft",
      "flexible",
      "woven",
      "rough-friendly",
      "worn-friendly",
    ],
  },
  {
    value: "felt",
    category: "fabric_textile",
    categoryLabel: "Fabric / Textile",
    categoryLabelKey: "modules.texture.categories.fabric_textile",
    promptText: "felt fabric material",
    tags: [
      "felt",
      "fabric",
      "textile",
      "soft",
      "flexible",
      "fibrous",
      "matte-friendly",
    ],
  },
  {
    value: "canvas",
    category: "fabric_textile",
    categoryLabel: "Fabric / Textile",
    categoryLabelKey: "modules.texture.categories.fabric_textile",
    promptText: "canvas fabric material",
    tags: [
      "canvas",
      "fabric",
      "textile",
      "soft",
      "flexible",
      "woven",
      "painted-friendly",
      "rough-friendly",
    ],
  },
  {
    value: "plush",
    category: "fabric_textile",
    categoryLabel: "Fabric / Textile",
    categoryLabelKey: "modules.texture.categories.fabric_textile",
    promptText: "plush fabric material",
    tags: [
      "plush",
      "fabric",
      "textile",
      "soft",
      "flexible",
      "toy-friendly",
      "fibrous",
      "velvety-friendly",
    ],
  },
  {
    value: "lace",
    category: "fabric_textile",
    categoryLabel: "Fabric / Textile",
    categoryLabelKey: "modules.texture.categories.fabric_textile",
    promptText: "lace fabric material",
    tags: [
      "lace",
      "fabric",
      "textile",
      "soft",
      "flexible",
      "woven",
      "delicate",
      "pattern-friendly",
    ],
  },

  // Leather / Hide
  {
    value: "leather",
    category: "leather_hide",
    categoryLabel: "Leather / Hide",
    categoryLabelKey: "modules.texture.categories.leather_hide",
    promptText: "leather material",
    tags: [
      "leather",
      "organic",
      "soft",
      "flexible",
      "opaque",
      "wrinkle-friendly",
      "scratch-friendly",
      "worn-friendly",
    ],
  },
  {
    value: "suede",
    category: "leather_hide",
    categoryLabel: "Leather / Hide",
    categoryLabelKey: "modules.texture.categories.leather_hide",
    promptText: "suede leather material",
    tags: [
      "suede",
      "leather",
      "organic",
      "soft",
      "flexible",
      "opaque",
      "velvety-friendly",
      "matte-friendly",
    ],
  },
  {
    value: "faux_leather",
    category: "leather_hide",
    categoryLabel: "Leather / Hide",
    categoryLabelKey: "modules.texture.categories.leather_hide",
    promptText: "faux leather material",
    tags: [
      "faux-leather",
      "leather",
      "synthetic",
      "soft",
      "flexible",
      "opaque",
      "gloss-friendly",
      "wrinkle-friendly",
    ],
  },

  // Paper / Cardboard
  {
    value: "paper",
    category: "paper_cardboard",
    categoryLabel: "Paper / Cardboard",
    categoryLabelKey: "modules.texture.categories.paper_cardboard",
    promptText: "paper material",
    tags: [
      "paper",
      "organic",
      "thin",
      "flexible",
      "opaque",
      "matte-friendly",
      "fibrous",
      "wrinkle-friendly",
    ],
  },
  {
    value: "cardboard",
    category: "paper_cardboard",
    categoryLabel: "Paper / Cardboard",
    categoryLabelKey: "modules.texture.categories.paper_cardboard",
    promptText: "cardboard material",
    tags: [
      "cardboard",
      "paper",
      "organic",
      "rigid",
      "opaque",
      "fibrous",
      "matte-friendly",
      "layered",
    ],
  },
  {
    value: "kraft_paper",
    category: "paper_cardboard",
    categoryLabel: "Paper / Cardboard",
    categoryLabelKey: "modules.texture.categories.paper_cardboard",
    promptText: "kraft paper material",
    tags: [
      "kraft",
      "paper",
      "organic",
      "thin",
      "flexible",
      "opaque",
      "fibrous",
      "matte-friendly",
      "handmade-friendly",
    ],
  },
  {
    value: "parchment",
    category: "paper_cardboard",
    categoryLabel: "Paper / Cardboard",
    categoryLabelKey: "modules.texture.categories.paper_cardboard",
    promptText: "parchment paper material",
    tags: [
      "parchment",
      "paper",
      "organic",
      "thin",
      "flexible",
      "translucent-friendly",
      "aged-friendly",
      "wrinkle-friendly",
    ],
  },

  // Rubber
  {
    value: "rubber",
    category: "rubber",
    categoryLabel: "Rubber",
    categoryLabelKey: "modules.texture.categories.rubber",
    promptText: "rubber material",
    tags: [
      "rubber",
      "synthetic",
      "soft",
      "flexible",
      "opaque",
      "matte-friendly",
      "rubbery",
    ],
  },
  {
    value: "latex",
    category: "rubber",
    categoryLabel: "Rubber",
    categoryLabelKey: "modules.texture.categories.rubber",
    promptText: "latex rubber material",
    tags: [
      "latex",
      "rubber",
      "synthetic",
      "soft",
      "flexible",
      "opaque",
      "gloss-friendly",
      "stretchy",
    ],
  },
  {
    value: "neoprene",
    category: "rubber",
    categoryLabel: "Rubber",
    categoryLabelKey: "modules.texture.categories.rubber",
    promptText: "neoprene rubber material",
    tags: [
      "neoprene",
      "rubber",
      "synthetic",
      "soft",
      "flexible",
      "opaque",
      "matte-friendly",
      "industrial",
    ],
  },

  // Organic / Natural
  {
    value: "bone",
    category: "organic_natural",
    categoryLabel: "Organic / Natural",
    categoryLabelKey: "modules.texture.categories.organic_natural",
    promptText: "bone material",
    tags: [
      "bone",
      "organic",
      "rigid",
      "opaque",
      "smooth-friendly",
      "aged-friendly",
      "carvable",
    ],
  },
  {
    value: "ivory",
    category: "organic_natural",
    categoryLabel: "Organic / Natural",
    categoryLabelKey: "modules.texture.categories.organic_natural",
    promptText: "ivory-like material",
    tags: [
      "ivory",
      "organic",
      "rigid",
      "opaque",
      "smooth-friendly",
      "carvable",
      "aged-friendly",
    ],
  },
  {
    value: "shell",
    category: "organic_natural",
    categoryLabel: "Organic / Natural",
    categoryLabelKey: "modules.texture.categories.organic_natural",
    promptText: "shell material",
    tags: [
      "shell",
      "organic",
      "rigid",
      "fragile",
      "opaque",
      "pearl-friendly",
      "smooth-friendly",
    ],
  },
  {
    value: "coral",
    category: "organic_natural",
    categoryLabel: "Organic / Natural",
    categoryLabelKey: "modules.texture.categories.organic_natural",
    promptText: "coral material",
    tags: [
      "coral",
      "organic",
      "rigid",
      "porous",
      "opaque",
      "grainable",
      "natural",
    ],
  },
  {
    value: "wax",
    category: "organic_natural",
    categoryLabel: "Organic / Natural",
    categoryLabelKey: "modules.texture.categories.organic_natural",
    promptText: "wax material",
    tags: [
      "wax",
      "organic",
      "soft",
      "translucent-friendly",
      "smooth-friendly",
      "waxy",
      "sculptural",
    ],
  },
];

const surfaceOptions = [
  {
    value: "smooth",
    promptText: "smooth clean surface",
    tags: ["smooth", "clean"],
    compatibility: {
      preferredTags: ["plastic", "vinyl", "metal", "glass", "ceramic", "resin"],
      supportedTags: ["wood", "stone", "paper", "leather", "clay"],
      warningKey: "modules.texture.warnings.surface_smooth",
    },
  },
  {
    value: "matte",
    promptText: "matte non-reflective surface",
    tags: ["matte", "non-reflective"],
    compatibility: {
      preferredTags: [
        "paper",
        "fabric",
        "clay",
        "ceramic",
        "wood",
        "rubber",
        "plastic",
      ],
      supportedTags: ["metal", "glass", "stone"],
      warningKey: "modules.texture.warnings.surface_matte",
    },
  },
  {
    value: "glossy",
    promptText: "glossy reflective surface",
    tags: ["glossy", "reflective"],
    compatibility: {
      preferredTags: ["glass", "ceramic", "plastic", "vinyl", "resin", "metal"],
      supportedTags: ["wood", "paper", "leather"],
      discouragedTags: ["fabric", "porous", "rough"],
      warningKey: "modules.texture.warnings.surface_glossy",
    },
  },
  {
    value: "high_gloss",
    promptText: "high-gloss mirror-like surface",
    tags: ["high-gloss", "mirror-like", "reflective"],
    compatibility: {
      preferredTags: ["glass", "metal", "ceramic", "resin", "plastic"],
      supportedTags: ["wood", "paper"],
      discouragedTags: ["fabric", "rubber", "porous", "organic"],
      warningKey: "modules.texture.warnings.surface_high_gloss",
    },
  },
  {
    value: "brushed",
    promptText: "brushed directional surface texture",
    tags: ["brushed", "directional"],
    compatibility: {
      preferredTags: ["metal"],
      supportedTags: ["wood", "plastic"],
      discouragedTags: ["fabric", "glass", "rubber", "paper"],
      warningKey: "modules.texture.warnings.surface_brushed",
    },
  },
  {
    value: "rough",
    promptText: "rough tactile surface",
    tags: ["rough", "tactile"],
    compatibility: {
      preferredTags: ["wood", "stone", "clay", "paper"],
      supportedTags: ["metal", "plastic", "ceramic"],
      discouragedTags: ["glass", "fabric"],
      warningKey: "modules.texture.warnings.surface_rough",
    },
  },
  {
    value: "porous",
    promptText: "subtly porous tactile surface",
    tags: ["porous", "tactile"],
    compatibility: {
      preferredTags: ["clay", "ceramic", "stone", "paper", "wood"],
      supportedTags: ["rubber", "organic"],
      discouragedTags: ["glass", "metal"],
      warningKey: "modules.texture.warnings.surface_porous",
    },
  },
  {
    value: "grainy",
    promptText: "fine grainy surface texture",
    tags: ["grainy", "fine-grain"],
    compatibility: {
      preferredTags: ["wood", "clay", "stone", "paper", "organic"],
      supportedTags: ["ceramic", "plastic"],
      discouragedTags: ["glass", "metal"],
      warningKey: "modules.texture.warnings.surface_grainy",
    },
  },
  {
    value: "fibrous",
    promptText: "fibrous tactile surface",
    tags: ["fibrous", "tactile"],
    compatibility: {
      preferredTags: ["fabric", "paper", "wood", "organic"],
      supportedTags: ["leather"],
      discouragedTags: ["metal", "glass", "ceramic"],
      warningKey: "modules.texture.warnings.surface_fibrous",
    },
  },
  {
    value: "woven",
    promptText: "woven surface texture",
    tags: ["woven", "texture"],
    compatibility: {
      preferredTags: ["fabric", "textile", "woven"],
      supportedTags: ["paper"],
      discouragedTags: ["metal", "glass", "stone", "ceramic", "plastic"],
      warningKey: "modules.texture.warnings.surface_woven",
    },
  },
  {
    value: "translucent",
    promptText: "translucent light-passing surface",
    tags: ["translucent", "light-passing"],
    compatibility: {
      preferredTags: ["glass", "crystal", "resin", "plastic", "translucent"],
      supportedTags: ["wax", "shell"],
      discouragedTags: ["wood", "metal", "fabric", "stone", "paper"],
      warningKey: "modules.texture.warnings.surface_translucent",
    },
  },
  {
    value: "frosted",
    promptText: "frosted diffused surface",
    tags: ["frosted", "diffused"],
    compatibility: {
      preferredTags: ["glass", "crystal", "plastic", "resin"],
      supportedTags: ["metal"],
      discouragedTags: ["wood", "fabric", "paper", "leather"],
      warningKey: "modules.texture.warnings.surface_frosted",
    },
  },
];

const detailLevelOptions = [
  {
    value: "minimal",
    promptText: "minimal surface detail",
    tags: ["minimal", "clean"],
    compatibility: {
      preferredTags: [
        "glass",
        "metal",
        "ceramic",
        "plastic",
        "vinyl",
        "resin",
        "smooth-friendly",
        "clean-friendly",
      ],
      supportedTags: [
        "wood",
        "paper",
        "fabric",
        "leather",
        "stone",
        "clay",
        "rubber",
      ],
    },
  },
  {
    value: "subtle",
    promptText: "subtle surface detail",
    tags: ["subtle", "controlled"],
    compatibility: {
      preferredTags: [
        "glass",
        "metal",
        "ceramic",
        "plastic",
        "vinyl",
        "resin",
        "rubber",
        "leather",
      ],
      supportedTags: ["wood", "paper", "fabric", "stone", "clay", "organic"],
    },
  },
  {
    value: "visible",
    promptText: "visible handcrafted surface detail",
    tags: ["visible", "handcrafted"],
    compatibility: {
      preferredTags: [
        "clay",
        "ceramic",
        "wood",
        "paper",
        "fabric",
        "leather",
        "stone",
        "organic",
        "handmade-friendly",
      ],
      supportedTags: ["plastic", "vinyl", "metal", "rubber", "resin"],
    },
  },
  {
    value: "rich",
    promptText: "rich detailed texture variation",
    tags: ["rich", "detailed", "variation"],
    compatibility: {
      preferredTags: [
        "wood",
        "stone",
        "clay",
        "ceramic",
        "fabric",
        "leather",
        "paper",
        "organic",
        "grainable",
        "fibrous",
        "woven",
      ],
      supportedTags: ["metal", "plastic", "vinyl", "rubber", "resin", "glass"],
    },
  },
  {
    value: "highly_detailed",
    promptText: "highly detailed tactile surface texture",
    tags: ["highly-detailed", "tactile", "surface-texture"],
    compatibility: {
      preferredTags: [
        "wood",
        "stone",
        "clay",
        "ceramic",
        "fabric",
        "leather",
        "paper",
        "organic",
        "grainable",
        "porous",
        "fibrous",
        "woven",
        "sculptural",
      ],
      supportedTags: ["metal", "plastic", "vinyl", "resin", "rubber", "glass"],
    },
  },
  {
    value: "intricate",
    promptText: "intricate fine-grained surface detail",
    tags: ["intricate", "fine-grained", "detailed"],
    compatibility: {
      preferredTags: [
        "wood",
        "stone",
        "clay",
        "ceramic",
        "paper",
        "organic",
        "grainable",
        "carvable",
        "faceted-friendly",
      ],
      supportedTags: [
        "metal",
        "resin",
        "plastic",
        "glass",
        "crystal",
        "leather",
      ],
      discouragedTags: ["fabric", "rubber"],
      warningKey: "modules.texture.warnings.detail_intricate",
    },
  },
  {
    value: "coarse",
    promptText: "coarse rough surface texture",
    tags: ["coarse", "rough", "tactile"],
    compatibility: {
      preferredTags: [
        "stone",
        "clay",
        "wood",
        "concrete",
        "paper",
        "organic",
        "porous",
        "rough-friendly",
      ],
      supportedTags: ["metal", "plastic", "ceramic", "rubber"],
      discouragedTags: [
        "glass",
        "crystal",
        "silk",
        "velvet",
        "smooth-friendly",
        "gloss-friendly",
      ],
      warningKey: "modules.texture.warnings.detail_coarse",
    },
  },
];

const imperfectionOptions = [
  {
    value: "clean",
    promptText: "flawless clean finish",
    tags: ["clean", "pristine", "flawless"],
    compatibility: {
      preferredTags: [
        "plastic",
        "vinyl",
        "glass",
        "ceramic",
        "metal",
        "resin",
        "rubber",
        "smooth-friendly",
        "clean-friendly",
      ],
      supportedTags: [
        "wood",
        "paper",
        "fabric",
        "leather",
        "stone",
        "clay",
        "organic",
      ],
    },
  },
  {
    value: "handmade",
    promptText: "small handmade imperfections",
    tags: ["handmade", "artisanal", "imperfect"],
    compatibility: {
      preferredTags: [
        "clay",
        "ceramic",
        "wood",
        "paper",
        "fabric",
        "leather",
        "stone",
        "organic",
        "handmade-friendly",
        "carvable",
      ],
      supportedTags: ["plastic", "resin", "metal", "rubber"],
    },
  },
  {
    value: "grain",
    promptText: "fine surface grain",
    tags: ["grain", "fine-grain", "grainy"],
    compatibility: {
      preferredTags: [
        "wood",
        "stone",
        "clay",
        "ceramic",
        "paper",
        "organic",
        "grainable",
        "porous",
      ],
      supportedTags: ["plastic", "resin", "rubber", "metal"],
      discouragedTags: [
        "glass",
        "crystal",
        "silk",
        "smooth-friendly",
        "gloss-friendly",
      ],
      warningKey: "modules.texture.warnings.imperfection_grain",
    },
  },
  {
    value: "brush_marks",
    promptText: "visible brush marks",
    tags: ["brush-marks", "painted", "handmade"],
    compatibility: {
      preferredTags: [
        "painted-friendly",
        "canvas",
        "paper",
        "wood",
        "clay",
        "ceramic",
        "handmade-friendly",
      ],
      supportedTags: ["plastic", "metal", "resin", "stone"],
      discouragedTags: ["glass", "crystal", "fabric", "rubber"],
      warningKey: "modules.texture.warnings.imperfection_brush_marks",
    },
  },
  {
    value: "paint_splatter",
    promptText: "stylized paint splatter details",
    tags: ["paint-splatter", "painted", "decorative"],
    compatibility: {
      preferredTags: [
        "paper",
        "canvas",
        "wood",
        "plastic",
        "resin",
        "painted-friendly",
        "toy-friendly",
      ],
      supportedTags: ["metal", "ceramic", "clay", "stone"],
      discouragedTags: ["glass", "fabric", "leather", "rubber"],
      warningKey: "modules.texture.warnings.imperfection_paint_splatter",
    },
  },
  {
    value: "scratches",
    promptText: "small scratches on the surface",
    tags: ["scratches", "worn", "surface-marks"],
    compatibility: {
      preferredTags: [
        "metal",
        "plastic",
        "glass",
        "wood",
        "leather",
        "resin",
        "scratch-friendly",
      ],
      supportedTags: ["ceramic", "stone", "rubber", "bone", "ivory"],
      discouragedTags: ["fabric", "paper", "soft", "woven"],
      warningKey: "modules.texture.warnings.imperfection_scratches",
    },
  },
  {
    value: "cracks",
    promptText: "cracked surface texture",
    tags: ["cracks", "aged", "surface-breaks"],
    compatibility: {
      preferredTags: [
        "clay",
        "ceramic",
        "stone",
        "wood",
        "concrete",
        "bone",
        "painted-friendly",
        "fragile",
      ],
      supportedTags: ["glass", "plastic", "resin", "paper"],
      discouragedTags: ["fabric", "rubber", "metal", "soft", "flexible"],
      warningKey: "modules.texture.warnings.imperfection_cracks",
    },
  },
  {
    value: "dents",
    promptText: "small dents or bumps",
    tags: ["dents", "bumps", "imperfect"],
    compatibility: {
      preferredTags: [
        "metal",
        "plastic",
        "rubber",
        "leather",
        "clay",
        "soft",
        "flexible",
      ],
      supportedTags: ["wood", "stone", "ceramic", "resin"],
      discouragedTags: ["glass", "crystal", "paper", "fabric"],
      warningKey: "modules.texture.warnings.imperfection_dents",
    },
  },
  {
    value: "chips",
    promptText: "chipped edges or surface",
    tags: ["chips", "chipped", "imperfect"],
    compatibility: {
      preferredTags: [
        "ceramic",
        "clay",
        "stone",
        "wood",
        "concrete",
        "glass",
        "painted-friendly",
        "fragile",
      ],
      supportedTags: ["metal", "plastic", "resin", "bone"],
      discouragedTags: ["fabric", "rubber", "paper", "soft", "flexible"],
      warningKey: "modules.texture.warnings.imperfection_chips",
    },
  },
  {
    value: "dust",
    promptText: "subtle dust and dirt",
    tags: ["dust", "dirt", "aged"],
    compatibility: {
      preferredTags: [
        "wood",
        "stone",
        "clay",
        "ceramic",
        "paper",
        "fabric",
        "leather",
        "metal",
        "plastic",
        "organic",
      ],
      supportedTags: ["glass", "rubber", "resin"],
    },
  },
  {
    value: "weathered",
    promptText: "weathered aged surface",
    tags: ["weathered", "aged", "worn"],
    compatibility: {
      preferredTags: [
        "wood",
        "stone",
        "metal",
        "concrete",
        "leather",
        "paper",
        "clay",
        "ceramic",
        "organic",
        "weathered-friendly",
        "aged-friendly",
      ],
      supportedTags: ["plastic", "rubber", "fabric", "glass"],
    },
  },
  {
    value: "stains",
    promptText: "stained or uneven color spots",
    tags: ["stains", "uneven-color", "aged"],
    compatibility: {
      preferredTags: [
        "fabric",
        "paper",
        "wood",
        "leather",
        "stone",
        "clay",
        "ceramic",
        "concrete",
        "porous",
      ],
      supportedTags: ["plastic", "rubber", "metal", "resin"],
      discouragedTags: ["glass", "crystal", "chrome", "clean-friendly"],
      warningKey: "modules.texture.warnings.imperfection_stains",
    },
  },
  {
    value: "roughness",
    promptText: "rough uneven texture",
    tags: ["roughness", "uneven", "coarse"],
    compatibility: {
      preferredTags: [
        "stone",
        "clay",
        "wood",
        "paper",
        "concrete",
        "organic",
        "porous",
        "rough-friendly",
      ],
      supportedTags: ["metal", "plastic", "ceramic", "rubber"],
      discouragedTags: [
        "glass",
        "crystal",
        "silk",
        "velvet",
        "smooth-friendly",
      ],
      warningKey: "modules.texture.warnings.imperfection_roughness",
    },
  },
  {
    value: "fading",
    promptText: "faded surface color",
    tags: ["fading", "faded", "aged-color"],
    compatibility: {
      preferredTags: [
        "fabric",
        "paper",
        "leather",
        "wood",
        "plastic",
        "painted-friendly",
        "aged-friendly",
      ],
      supportedTags: ["metal", "rubber", "stone", "ceramic"],
      discouragedTags: ["glass", "crystal", "chrome"],
      warningKey: "modules.texture.warnings.imperfection_fading",
    },
  },
  {
    value: "wrinkles",
    promptText: "wrinkled or creased surface",
    tags: ["wrinkles", "creases", "folds"],
    compatibility: {
      preferredTags: [
        "fabric",
        "leather",
        "paper",
        "rubber",
        "soft",
        "flexible",
        "wrinkle-friendly",
      ],
      supportedTags: ["organic", "wax"],
      discouragedTags: ["metal", "glass", "stone", "ceramic", "wood", "rigid"],
      warningKey: "modules.texture.warnings.imperfection_wrinkles",
    },
  },
  {
    value: "peeling",
    promptText: "peeling or flaking surface",
    tags: ["peeling", "flaking", "weathered"],
    compatibility: {
      preferredTags: [
        "painted-friendly",
        "wood",
        "metal",
        "paper",
        "wall-like",
        "aged-friendly",
        "weathered-friendly",
      ],
      supportedTags: ["clay", "ceramic", "plastic", "leather", "concrete"],
      discouragedTags: ["glass", "fabric", "rubber", "crystal"],
      warningKey: "modules.texture.warnings.imperfection_peeling",
    },
  },
  {
    value: "corrosion",
    promptText: "corroded or oxidized surface",
    tags: ["corrosion", "rust", "oxidized"],
    compatibility: {
      preferredTags: [
        "metal",
        "iron",
        "steel",
        "copper",
        "brass",
        "bronze",
        "corrosion-friendly",
        "oxidation-friendly",
        "rust-friendly",
        "patina-friendly",
      ],
      supportedTags: ["industrial"],
      discouragedTags: [
        "wood",
        "fabric",
        "paper",
        "glass",
        "ceramic",
        "clay",
        "rubber",
        "plastic",
        "organic",
        "leather",
        "stone",
      ],
      warningKey: "modules.texture.warnings.imperfection_corrosion",
    },
  },
];

export const TextureModule: PromptKeyModule = {
  key: "texture",
  icon: "brush-2",
  groups: {
    material: { id: "material", order: 1, defaultOpen: true },
    surface: { id: "surface", order: 2, defaultOpen: false },
    advanced: { id: "advanced", order: 3, defaultOpen: false },
    override: { id: "override", order: 4, defaultOpen: false },
  },

  fields: {
    material: {
      id: "material",
      type: "select",
      default: "vinyl",
      group: "material",
      order: 10,
      options: materialOptions,
      ui: {
        component: "select",
        optionLayout: "categorized",
        searchable: true,
        clearable: true,
        width: "full",
      },
    },

    surface: {
      id: "surface",
      type: "select",
      default: "",
      group: "surface",
      order: 10,
      options: surfaceOptions,
      ui: {
        component: "select",
        searchable: true,
        clearable: true,
        width: "half",
        compatibility: {
          dependsOn: "material",
          mode: "sort-and-hint",
        },
      },
    },

    detailLevel: {
      id: "detailLevel",
      type: "select",
      default: "",
      group: "surface",
      order: 20,
      options: detailLevelOptions,
      ui: {
        component: "select",
        searchable: false,
        clearable: true,
        width: "half",
        compatibility: {
          dependsOn: "material",
          mode: "sort-and-hint",
        },
      },
    },

    imperfections: {
      id: "imperfections",
      type: "multiSelect",
      default: [],
      group: "advanced",
      order: 10,
      options: imperfectionOptions,
      ui: {
        component: "select",
        searchable: true,
        clearable: true,
        multiple: true,
        width: "full",
        compatibility: {
          dependsOn: "material",
          mode: "sort-and-hint",
        },
      },
    },

    extraDetails: {
      id: "extraDetails",
      type: "textarea",
      default: "",
      group: "advanced",
      order: 20,
      ui: {
        component: "textarea",
        rows: 3,
        width: "full",
      },
    },

    customText: {
      id: "customText",
      type: "textarea",
      default: "",
      group: "override",
      order: 10,
      isOverride: true,
      ui: {
        component: "textarea",
        rows: 4,
        width: "full",
      },
    },
  },

  presets: {
    smooth_vinyl: {
      id: "smooth_vinyl",
      order: 1,
      values: {
        material: "vinyl",
        surface: "smooth",
        detailLevel: "subtle",
        imperfections: ["clean"],
      },
    },

    handmade_clay: {
      id: "handmade_clay",
      order: 2,
      values: {
        material: "clay",
        surface: "porous",
        detailLevel: "visible",
        imperfections: ["handmade"],
      },
    },

    polished_metal: {
      id: "polished_metal",
      order: 3,
      values: {
        material: "metal",
        surface: "glossy",
        detailLevel: "subtle",
        imperfections: ["clean"],
      },
    },

    painterly_surface: {
      id: "painterly_surface",
      order: 4,
      values: {
        material: "plastic",
        surface: "matte",
        detailLevel: "rich",
        imperfections: ["brush_marks", "paint_splatter"],
      },
    },
  },

  compile: {
    separator: ", ",
    removeDuplicates: true,
    ignoreEmpty: true,
    overrideField: "customText",
  },
};
